import type { GoldenCard } from "./types";

export const GOLDEN_CARDS: GoldenCard[] = [
  {
    id: "greet-yuki",
    characterId: "yuki",
    segmentIds: ["jp-salary", "jp-family"],
    intents: ["greeting"],
    tags: ["greeting", "opener"],
    text: { ko: "안녕. 유키야. 배고프면 식사, 걷고 싶으면 동선, 조건 있으면 칩으로 먼저 골라 줘. 나는 미리 적어 둔 답 카드로 빠르게 맞춰 볼게.", en: "Hey — I am Yuki. Hungry, walking, or a constraint? Tap a chip first; I will match a prepared answer card before free chat." },
    chipFollowups: [{ ko: "밥 추천", en: "Food pick" }, { ko: "산책", en: "A walk" }, { ko: "조건 고르기", en: "Set constraints" }],
  },
  {
    id: "greet-tom",
    characterId: "tom",
    segmentIds: ["cn-mainland", "sea-worker", "en-backpacker", "eu-backpacker"],
    intents: ["greeting"],
    tags: ["greeting", "opener"],
    text: { ko: "안녕. 톰야. 배고프면 식사, 걷고 싶으면 동선, 조건 있으면 칩으로 먼저 골라 줘. 나는 미리 적어 둔 답 카드로 빠르게 맞춰 볼게.", en: "Hey — I am Tom. Hungry, walking, or a constraint? Tap a chip first; I will match a prepared answer card before free chat." },
    chipFollowups: [{ ko: "밥 추천", en: "Food pick" }, { ko: "산책", en: "A walk" }, { ko: "조건 고르기", en: "Set constraints" }],
  },
  {
    id: "greet-maya",
    characterId: "maya",
    segmentIds: ["sea-muslim-student", "sea-family", "me-biz"],
    intents: ["greeting"],
    tags: ["greeting", "opener"],
    text: { ko: "안녕. 마야야. 배고프면 식사, 걷고 싶으면 동선, 조건 있으면 칩으로 먼저 골라 줘. 나는 미리 적어 둔 답 카드로 빠르게 맞춰 볼게.", en: "Hey — I am Maya. Hungry, walking, or a constraint? Tap a chip first; I will match a prepared answer card before free chat." },
    chipFollowups: [{ ko: "밥 추천", en: "Food pick" }, { ko: "산책", en: "A walk" }, { ko: "조건 고르기", en: "Set constraints" }],
  },
  {
    id: "greet-nuri",
    characterId: "nuri",
    segmentIds: ["sea-wh", "en-worker", "ru-cis"],
    intents: ["greeting"],
    tags: ["greeting", "opener"],
    text: { ko: "안녕. 누리야. 배고프면 식사, 걷고 싶으면 동선, 조건 있으면 칩으로 먼저 골라 줘. 나는 미리 적어 둔 답 카드로 빠르게 맞춰 볼게.", en: "Hey — I am Nuri. Hungry, walking, or a constraint? Tap a chip first; I will match a prepared answer card before free chat." },
    chipFollowups: [{ ko: "밥 추천", en: "Food pick" }, { ko: "산책", en: "A walk" }, { ko: "조건 고르기", en: "Set constraints" }],
  },
  {
    id: "greet-sori",
    characterId: "sori",
    segmentIds: ["greater-china", "latam"],
    intents: ["greeting"],
    tags: ["greeting", "opener"],
    text: { ko: "안녕. 소리야. 배고프면 식사, 걷고 싶으면 동선, 조건 있으면 칩으로 먼저 골라 줘. 나는 미리 적어 둔 답 카드로 빠르게 맞춰 볼게.", en: "Hey — I am Sori. Hungry, walking, or a constraint? Tap a chip first; I will match a prepared answer card before free chat." },
    chipFollowups: [{ ko: "밥 추천", en: "Food pick" }, { ko: "산책", en: "A walk" }, { ko: "조건 고르기", en: "Set constraints" }],
  },
  {
    id: "greet-dal",
    characterId: "dal",
    segmentIds: ["eu-couple", "lgbtq-safe"],
    intents: ["greeting"],
    tags: ["greeting", "opener"],
    text: { ko: "안녕. 달야. 배고프면 식사, 걷고 싶으면 동선, 조건 있으면 칩으로 먼저 골라 줘. 나는 미리 적어 둔 답 카드로 빠르게 맞춰 볼게.", en: "Hey — I am Dal. Hungry, walking, or a constraint? Tap a chip first; I will match a prepared answer card before free chat." },
    chipFollowups: [{ ko: "밥 추천", en: "Food pick" }, { ko: "산책", en: "A walk" }, { ko: "조건 고르기", en: "Set constraints" }],
  },
  {
    id: "greet-rina",
    characterId: "rina",
    segmentIds: ["in-it"],
    intents: ["greeting"],
    tags: ["greeting", "opener"],
    text: { ko: "안녕. 리나야. 배고프면 식사, 걷고 싶으면 동선, 조건 있으면 칩으로 먼저 골라 줘. 나는 미리 적어 둔 답 카드로 빠르게 맞춰 볼게.", en: "Hey — I am Rina. Hungry, walking, or a constraint? Tap a chip first; I will match a prepared answer card before free chat." },
    chipFollowups: [{ ko: "밥 추천", en: "Food pick" }, { ko: "산책", en: "A walk" }, { ko: "조건 고르기", en: "Set constraints" }],
  },
  {
    id: "greet-hana",
    characterId: "hana",
    segmentIds: ["k-content"],
    intents: ["greeting"],
    tags: ["greeting", "opener"],
    text: { ko: "안녕. 하나야. 배고프면 식사, 걷고 싶으면 동선, 조건 있으면 칩으로 먼저 골라 줘. 나는 미리 적어 둔 답 카드로 빠르게 맞춰 볼게.", en: "Hey — I am Hana. Hungry, walking, or a constraint? Tap a chip first; I will match a prepared answer card before free chat." },
    chipFollowups: [{ ko: "밥 추천", en: "Food pick" }, { ko: "산책", en: "A walk" }, { ko: "조건 고르기", en: "Set constraints" }],
  },
  {
    id: "jp-salary-food-1",
    characterId: "yuki",
    segmentIds: ["jp-salary"],
    intents: ["food"],
    tags: ["food", "jp-salary", "yuki"],
    text: { ko: "유키 기준으로 지금 배고프면 진주집 쪽이 맞아. 일본 손님들이 자주 묻던 효율·맵기 기준으로 재료·영업은 방문 전에 한 번만 확인해 줘.", en: "With Yuki's taste, Jinju-jip fits a hungry turn. using the efficient, milder bar Yuki learned from JP guests Double-check hours and ingredients before you go." },
    placeHints: ["jinjujip"],
    chipFollowups: [{ ko: "다른 분위기", en: "Different vibe" }, { ko: "더 가까운 데", en: "Closer option" }, { ko: "예산은 어때?", en: "Budget check" }],
  },
  {
    id: "jp-salary-food-2",
    characterId: "yuki",
    segmentIds: ["jp-salary"],
    intents: ["food"],
    tags: ["food", "jp-salary", "yuki"],
    text: { ko: "유키 기준으로 지금 배고프면 을지로 우래옥 쪽이 맞아. 일본 손님들이 자주 묻던 효율·맵기 기준으로 재료·영업은 방문 전에 한 번만 확인해 줘.", en: "With Yuki's taste, Uraeok fits a hungry turn. using the efficient, milder bar Yuki learned from JP guests Double-check hours and ingredients before you go." },
    placeHints: ["uraeok"],
    chipFollowups: [{ ko: "다른 분위기", en: "Different vibe" }, { ko: "더 가까운 데", en: "Closer option" }, { ko: "예산은 어때?", en: "Budget check" }],
  },
  {
    id: "jp-salary-budget-1",
    characterId: "yuki",
    segmentIds: ["jp-salary"],
    intents: ["budget"],
    tags: ["budget", "jp-salary", "yuki"],
    text: { ko: "지갑 생각이면 광장시장부터. 일본 손님들이 자주 묻던 효율·맵기 기준으로 가격은 매장마다 다르니 메뉴판 기준으로만 말해 줄게.", en: "On a budget, start with Gwangjang Market. using the efficient, milder bar Yuki learned from JP guests I will not invent prices—use the menu you see." },
    placeHints: ["gwangjang"],
    chipFollowups: [{ ko: "더 싸게", en: "Cheaper still" }, { ko: "배부르게", en: "More filling" }, { ko: "걸어서 갈 수 있게", en: "Walkable" }],
  },
  {
    id: "jp-salary-budget-2",
    characterId: "yuki",
    segmentIds: ["jp-salary"],
    intents: ["budget"],
    tags: ["budget", "jp-salary", "yuki"],
    text: { ko: "지갑 생각이면 무학동 닭집부터. 일본 손님들이 자주 묻던 효율·맵기 기준으로 가격은 매장마다 다르니 메뉴판 기준으로만 말해 줄게.", en: "On a budget, start with Muhak chicken spot. using the efficient, milder bar Yuki learned from JP guests I will not invent prices—use the menu you see." },
    placeHints: ["muhak-dak"],
    chipFollowups: [{ ko: "더 싸게", en: "Cheaper still" }, { ko: "배부르게", en: "More filling" }, { ko: "걸어서 갈 수 있게", en: "Walkable" }],
  },
  {
    id: "jp-salary-cafe-1",
    characterId: "yuki",
    segmentIds: ["jp-salary"],
    intents: ["cafe"],
    tags: ["cafe", "jp-salary", "yuki"],
    text: { ko: "잠깐 쉬려면 성수 카페 거리가 무난해. 일본 손님들이 자주 묻던 효율·맵기 기준으로 웨이팅은 현장 기준으로만 봐 줘.", en: "For a short pause, Seongsu cafe streets works. using the efficient, milder bar Yuki learned from JP guests Treat wait times as on-site only." },
    placeHints: ["seongsu-onion"],
    chipFollowups: [{ ko: "디저트", en: "Dessert" }, { ko: "작업하기 좋게", en: "Good for laptop" }, { ko: "근처 산책", en: "Nearby walk" }],
  },
  {
    id: "jp-salary-cafe-2",
    characterId: "yuki",
    segmentIds: ["jp-salary"],
    intents: ["cafe"],
    tags: ["cafe", "jp-salary", "yuki"],
    text: { ko: "잠깐 쉬려면 커먼그라운드가 무난해. 일본 손님들이 자주 묻던 효율·맵기 기준으로 웨이팅은 현장 기준으로만 봐 줘.", en: "For a short pause, Common Ground works. using the efficient, milder bar Yuki learned from JP guests Treat wait times as on-site only." },
    placeHints: ["common-ground"],
    chipFollowups: [{ ko: "디저트", en: "Dessert" }, { ko: "작업하기 좋게", en: "Good for laptop" }, { ko: "근처 산책", en: "Nearby walk" }],
  },
  {
    id: "jp-salary-followup-1",
    characterId: "yuki",
    segmentIds: ["jp-salary"],
    intents: ["followup"],
    tags: ["followup", "jp-salary"],
    text: { ko: "좋아. 그다음으로는 진주집를 이어서 볼까, 아니면 조건을 바꿀까?", en: "Nice. Next we can stay with Jinju-jip, or change the constraint." },
    placeHints: ["jinjujip"],
    chipFollowups: [{ ko: "여기로 갈게", en: "I will go here" }, { ko: "다른 후보", en: "Another option" }, { ko: "조건 바꾸기", en: "Change filters" }],
  },
  {
    id: "jp-family-food-1",
    characterId: "yuki",
    segmentIds: ["jp-family"],
    intents: ["food"],
    tags: ["food", "jp-family", "yuki"],
    text: { ko: "유키 기준으로 지금 배고프면 진주집 쪽이 맞아. 일본 손님들이 자주 묻던 효율·맵기 기준으로 재료·영업은 방문 전에 한 번만 확인해 줘.", en: "With Yuki's taste, Jinju-jip fits a hungry turn. using the efficient, milder bar Yuki learned from JP guests Double-check hours and ingredients before you go." },
    placeHints: ["jinjujip"],
    chipFollowups: [{ ko: "다른 분위기", en: "Different vibe" }, { ko: "더 가까운 데", en: "Closer option" }, { ko: "예산은 어때?", en: "Budget check" }],
  },
  {
    id: "jp-family-food-2",
    characterId: "yuki",
    segmentIds: ["jp-family"],
    intents: ["food"],
    tags: ["food", "jp-family", "yuki"],
    text: { ko: "유키 기준으로 지금 배고프면 을지로 우래옥 쪽이 맞아. 일본 손님들이 자주 묻던 효율·맵기 기준으로 재료·영업은 방문 전에 한 번만 확인해 줘.", en: "With Yuki's taste, Uraeok fits a hungry turn. using the efficient, milder bar Yuki learned from JP guests Double-check hours and ingredients before you go." },
    placeHints: ["uraeok"],
    chipFollowups: [{ ko: "다른 분위기", en: "Different vibe" }, { ko: "더 가까운 데", en: "Closer option" }, { ko: "예산은 어때?", en: "Budget check" }],
  },
  {
    id: "jp-family-group-1",
    characterId: "yuki",
    segmentIds: ["jp-family"],
    intents: ["group"],
    tags: ["group", "jp-family", "yuki"],
    text: { ko: "여럿이라면 광장시장처럼 나눠 먹기 쉬운 쪽이 편해. 일본 손님들이 자주 묻던 효율·맵기 기준으로", en: "For a small group, shareable spots like Gwangjang Market are easier. using the efficient, milder bar Yuki learned from JP guests" },
    placeHints: ["gwangjang"],
    chipFollowups: [{ ko: "맵기 낮게", en: "Milder spice" }, { ko: "아이 배려", en: "Kid-friendly" }, { ko: "예약 필요할까?", en: "Need a booking?" }],
  },
  {
    id: "jp-family-group-2",
    characterId: "yuki",
    segmentIds: ["jp-family"],
    intents: ["group"],
    tags: ["group", "jp-family", "yuki"],
    text: { ko: "여럿이라면 을지로 우래옥처럼 나눠 먹기 쉬운 쪽이 편해. 일본 손님들이 자주 묻던 효율·맵기 기준으로", en: "For a small group, shareable spots like Uraeok are easier. using the efficient, milder bar Yuki learned from JP guests" },
    placeHints: ["uraeok"],
    chipFollowups: [{ ko: "맵기 낮게", en: "Milder spice" }, { ko: "아이 배려", en: "Kid-friendly" }, { ko: "예약 필요할까?", en: "Need a booking?" }],
  },
  {
    id: "jp-family-walk-1",
    characterId: "yuki",
    segmentIds: ["jp-family"],
    intents: ["walk"],
    tags: ["walk", "jp-family", "yuki"],
    text: { ko: "걷기 좋은 코스로는 서울숲가 무난해. 일본 손님들이 자주 묻던 효율·맵기 기준으로 비 오면 실내로 바로 바꿔 줄게.", en: "For a walkable stretch, Seoul Forest is steady. using the efficient, milder bar Yuki learned from JP guests If it rains we switch indoors." },
    placeHints: ["seoul-forest"],
    chipFollowups: [{ ko: "더 조용하게", en: "Quieter path" }, { ko: "짧게만", en: "Keep it short" }, { ko: "카페로 이어서", en: "Then a cafe" }],
  },
  {
    id: "jp-family-walk-2",
    characterId: "yuki",
    segmentIds: ["jp-family"],
    intents: ["walk"],
    tags: ["walk", "jp-family", "yuki"],
    text: { ko: "걷기 좋은 코스로는 뚝섬한강공원가 무난해. 일본 손님들이 자주 묻던 효율·맵기 기준으로 비 오면 실내로 바로 바꿔 줄게.", en: "For a walkable stretch, Ttukseom Hangang Park is steady. using the efficient, milder bar Yuki learned from JP guests If it rains we switch indoors." },
    placeHints: ["ttukseom"],
    chipFollowups: [{ ko: "더 조용하게", en: "Quieter path" }, { ko: "짧게만", en: "Keep it short" }, { ko: "카페로 이어서", en: "Then a cafe" }],
  },
  {
    id: "jp-family-followup-1",
    characterId: "yuki",
    segmentIds: ["jp-family"],
    intents: ["followup"],
    tags: ["followup", "jp-family"],
    text: { ko: "좋아. 그다음으로는 진주집를 이어서 볼까, 아니면 조건을 바꿀까?", en: "Nice. Next we can stay with Jinju-jip, or change the constraint." },
    placeHints: ["jinjujip"],
    chipFollowups: [{ ko: "여기로 갈게", en: "I will go here" }, { ko: "다른 후보", en: "Another option" }, { ko: "조건 바꾸기", en: "Change filters" }],
  },
  {
    id: "cn-mainland-food-1",
    characterId: "tom",
    segmentIds: ["cn-mainland"],
    intents: ["food"],
    tags: ["food", "cn-mainland", "tom"],
    text: { ko: "톰 기준으로 지금 배고프면 진주집 쪽이 맞아. 값어치와 배부름을 먼저 보는 기준으로 재료·영업은 방문 전에 한 번만 확인해 줘.", en: "With Tom's taste, Jinju-jip fits a hungry turn. favoring value and fullness the way Tom ranks Double-check hours and ingredients before you go." },
    placeHints: ["jinjujip"],
    chipFollowups: [{ ko: "다른 분위기", en: "Different vibe" }, { ko: "더 가까운 데", en: "Closer option" }, { ko: "예산은 어때?", en: "Budget check" }],
  },
  {
    id: "cn-mainland-food-2",
    characterId: "tom",
    segmentIds: ["cn-mainland"],
    intents: ["food"],
    tags: ["food", "cn-mainland", "tom"],
    text: { ko: "톰 기준으로 지금 배고프면 을지로 우래옥 쪽이 맞아. 값어치와 배부름을 먼저 보는 기준으로 재료·영업은 방문 전에 한 번만 확인해 줘.", en: "With Tom's taste, Uraeok fits a hungry turn. favoring value and fullness the way Tom ranks Double-check hours and ingredients before you go." },
    placeHints: ["uraeok"],
    chipFollowups: [{ ko: "다른 분위기", en: "Different vibe" }, { ko: "더 가까운 데", en: "Closer option" }, { ko: "예산은 어때?", en: "Budget check" }],
  },
  {
    id: "cn-mainland-budget-1",
    characterId: "tom",
    segmentIds: ["cn-mainland"],
    intents: ["budget"],
    tags: ["budget", "cn-mainland", "tom"],
    text: { ko: "지갑 생각이면 광장시장부터. 값어치와 배부름을 먼저 보는 기준으로 가격은 매장마다 다르니 메뉴판 기준으로만 말해 줄게.", en: "On a budget, start with Gwangjang Market. favoring value and fullness the way Tom ranks I will not invent prices—use the menu you see." },
    placeHints: ["gwangjang"],
    chipFollowups: [{ ko: "더 싸게", en: "Cheaper still" }, { ko: "배부르게", en: "More filling" }, { ko: "걸어서 갈 수 있게", en: "Walkable" }],
  },
  {
    id: "cn-mainland-budget-2",
    characterId: "tom",
    segmentIds: ["cn-mainland"],
    intents: ["budget"],
    tags: ["budget", "cn-mainland", "tom"],
    text: { ko: "지갑 생각이면 무학동 닭집부터. 값어치와 배부름을 먼저 보는 기준으로 가격은 매장마다 다르니 메뉴판 기준으로만 말해 줄게.", en: "On a budget, start with Muhak chicken spot. favoring value and fullness the way Tom ranks I will not invent prices—use the menu you see." },
    placeHints: ["muhak-dak"],
    chipFollowups: [{ ko: "더 싸게", en: "Cheaper still" }, { ko: "배부르게", en: "More filling" }, { ko: "걸어서 갈 수 있게", en: "Walkable" }],
  },
  {
    id: "cn-mainland-night-1",
    characterId: "tom",
    segmentIds: ["cn-mainland"],
    intents: ["night"],
    tags: ["night", "cn-mainland", "tom"],
    text: { ko: "늦은 시간이면 톰는 을지로 노가리를 먼저 떠올려. 값어치와 배부름을 먼저 보는 기준으로 너무 늦으면 영업 마감만 확인하고 가자.", en: "For a late hour, Tom leans Euljiro nogari alley. favoring value and fullness the way Tom ranks Confirm closing time if it is already late." },
    placeHints: ["euljiro-nogari"],
    chipFollowups: [{ ko: "야식 가볍게", en: "Lighter late bite" }, { ko: "산책으로 바꿀까", en: "Switch to a walk" }, { ko: "다른 밤 코스", en: "Another night pick" }],
  },
  {
    id: "cn-mainland-night-2",
    characterId: "tom",
    segmentIds: ["cn-mainland"],
    intents: ["night"],
    tags: ["night", "cn-mainland", "tom"],
    text: { ko: "늦은 시간이면 톰는 낙산공원를 먼저 떠올려. 값어치와 배부름을 먼저 보는 기준으로 너무 늦으면 영업 마감만 확인하고 가자.", en: "For a late hour, Tom leans Naksan Park. favoring value and fullness the way Tom ranks Confirm closing time if it is already late." },
    placeHints: ["naksan"],
    chipFollowups: [{ ko: "야식 가볍게", en: "Lighter late bite" }, { ko: "산책으로 바꿀까", en: "Switch to a walk" }, { ko: "다른 밤 코스", en: "Another night pick" }],
  },
  {
    id: "cn-mainland-followup-1",
    characterId: "tom",
    segmentIds: ["cn-mainland"],
    intents: ["followup"],
    tags: ["followup", "cn-mainland"],
    text: { ko: "좋아. 그다음으로는 진주집를 이어서 볼까, 아니면 조건을 바꿀까?", en: "Nice. Next we can stay with Jinju-jip, or change the constraint." },
    placeHints: ["jinjujip"],
    chipFollowups: [{ ko: "여기로 갈게", en: "I will go here" }, { ko: "다른 후보", en: "Another option" }, { ko: "조건 바꾸기", en: "Change filters" }],
  },
  {
    id: "greater-china-food-1",
    characterId: "sori",
    segmentIds: ["greater-china"],
    intents: ["food"],
    tags: ["food", "greater-china", "sori"],
    text: { ko: "소리 기준으로 지금 배고프면 진주집 쪽이 맞아. 관광 함정보다 취향을 우선하는 기준으로 재료·영업은 방문 전에 한 번만 확인해 줘.", en: "With Sori's taste, Jinju-jip fits a hungry turn. preferring taste over tourist traps like Sori Double-check hours and ingredients before you go." },
    placeHints: ["jinjujip"],
    chipFollowups: [{ ko: "다른 분위기", en: "Different vibe" }, { ko: "더 가까운 데", en: "Closer option" }, { ko: "예산은 어때?", en: "Budget check" }],
  },
  {
    id: "greater-china-food-2",
    characterId: "sori",
    segmentIds: ["greater-china"],
    intents: ["food"],
    tags: ["food", "greater-china", "sori"],
    text: { ko: "소리 기준으로 지금 배고프면 을지로 우래옥 쪽이 맞아. 관광 함정보다 취향을 우선하는 기준으로 재료·영업은 방문 전에 한 번만 확인해 줘.", en: "With Sori's taste, Uraeok fits a hungry turn. preferring taste over tourist traps like Sori Double-check hours and ingredients before you go." },
    placeHints: ["uraeok"],
    chipFollowups: [{ ko: "다른 분위기", en: "Different vibe" }, { ko: "더 가까운 데", en: "Closer option" }, { ko: "예산은 어때?", en: "Budget check" }],
  },
  {
    id: "greater-china-cafe-1",
    characterId: "sori",
    segmentIds: ["greater-china"],
    intents: ["cafe"],
    tags: ["cafe", "greater-china", "sori"],
    text: { ko: "잠깐 쉬려면 성수 카페 거리가 무난해. 관광 함정보다 취향을 우선하는 기준으로 웨이팅은 현장 기준으로만 봐 줘.", en: "For a short pause, Seongsu cafe streets works. preferring taste over tourist traps like Sori Treat wait times as on-site only." },
    placeHints: ["seongsu-onion"],
    chipFollowups: [{ ko: "디저트", en: "Dessert" }, { ko: "작업하기 좋게", en: "Good for laptop" }, { ko: "근처 산책", en: "Nearby walk" }],
  },
  {
    id: "greater-china-cafe-2",
    characterId: "sori",
    segmentIds: ["greater-china"],
    intents: ["cafe"],
    tags: ["cafe", "greater-china", "sori"],
    text: { ko: "잠깐 쉬려면 커먼그라운드가 무난해. 관광 함정보다 취향을 우선하는 기준으로 웨이팅은 현장 기준으로만 봐 줘.", en: "For a short pause, Common Ground works. preferring taste over tourist traps like Sori Treat wait times as on-site only." },
    placeHints: ["common-ground"],
    chipFollowups: [{ ko: "디저트", en: "Dessert" }, { ko: "작업하기 좋게", en: "Good for laptop" }, { ko: "근처 산책", en: "Nearby walk" }],
  },
  {
    id: "greater-china-walk-1",
    characterId: "sori",
    segmentIds: ["greater-china"],
    intents: ["walk"],
    tags: ["walk", "greater-china", "sori"],
    text: { ko: "걷기 좋은 코스로는 서울숲가 무난해. 관광 함정보다 취향을 우선하는 기준으로 비 오면 실내로 바로 바꿔 줄게.", en: "For a walkable stretch, Seoul Forest is steady. preferring taste over tourist traps like Sori If it rains we switch indoors." },
    placeHints: ["seoul-forest"],
    chipFollowups: [{ ko: "더 조용하게", en: "Quieter path" }, { ko: "짧게만", en: "Keep it short" }, { ko: "카페로 이어서", en: "Then a cafe" }],
  },
  {
    id: "greater-china-walk-2",
    characterId: "sori",
    segmentIds: ["greater-china"],
    intents: ["walk"],
    tags: ["walk", "greater-china", "sori"],
    text: { ko: "걷기 좋은 코스로는 뚝섬한강공원가 무난해. 관광 함정보다 취향을 우선하는 기준으로 비 오면 실내로 바로 바꿔 줄게.", en: "For a walkable stretch, Ttukseom Hangang Park is steady. preferring taste over tourist traps like Sori If it rains we switch indoors." },
    placeHints: ["ttukseom"],
    chipFollowups: [{ ko: "더 조용하게", en: "Quieter path" }, { ko: "짧게만", en: "Keep it short" }, { ko: "카페로 이어서", en: "Then a cafe" }],
  },
  {
    id: "greater-china-followup-1",
    characterId: "sori",
    segmentIds: ["greater-china"],
    intents: ["followup"],
    tags: ["followup", "greater-china"],
    text: { ko: "좋아. 그다음으로는 진주집를 이어서 볼까, 아니면 조건을 바꿀까?", en: "Nice. Next we can stay with Jinju-jip, or change the constraint." },
    placeHints: ["jinjujip"],
    chipFollowups: [{ ko: "여기로 갈게", en: "I will go here" }, { ko: "다른 후보", en: "Another option" }, { ko: "조건 바꾸기", en: "Change filters" }],
  },
  {
    id: "sea-muslim-student-halal-1",
    characterId: "maya",
    segmentIds: ["sea-muslim-student"],
    intents: ["halal"],
    tags: ["halal", "sea-muslim-student", "maya"],
    text: { ko: "돼지고기 빼는 흐름이면 이태원 케밥를 먼저 볼게. 할랄 인증·조리 도구·알코올은 별도 확인이 필요해.", en: "For a pork-free path, I look at Itaewon kebab first. Halal certification, utensils, and alcohol need separate checks." },
    placeHints: ["itaewon-kebab"],
    chipFollowups: [{ ko: "다른 무돼지고기", en: "Another no-pork" }, { ko: "야식도 괜찮아?", en: "Late-night OK?" }, { ko: "채식에 가깝게", en: "Closer to veg" }],
  },
  {
    id: "sea-muslim-student-food-1",
    characterId: "maya",
    segmentIds: ["sea-muslim-student"],
    intents: ["food"],
    tags: ["food", "sea-muslim-student", "maya"],
    text: { ko: "마야 기준으로 지금 배고프면 진주집 쪽이 맞아. 식사 제약을 먼저 챙기는 기준으로 재료·영업은 방문 전에 한 번만 확인해 줘.", en: "With Maya's taste, Jinju-jip fits a hungry turn. leading with dining constraints the way Maya does Double-check hours and ingredients before you go." },
    placeHints: ["jinjujip"],
    chipFollowups: [{ ko: "다른 분위기", en: "Different vibe" }, { ko: "더 가까운 데", en: "Closer option" }, { ko: "예산은 어때?", en: "Budget check" }],
  },
  {
    id: "sea-muslim-student-food-2",
    characterId: "maya",
    segmentIds: ["sea-muslim-student"],
    intents: ["food"],
    tags: ["food", "sea-muslim-student", "maya"],
    text: { ko: "마야 기준으로 지금 배고프면 을지로 우래옥 쪽이 맞아. 식사 제약을 먼저 챙기는 기준으로 재료·영업은 방문 전에 한 번만 확인해 줘.", en: "With Maya's taste, Uraeok fits a hungry turn. leading with dining constraints the way Maya does Double-check hours and ingredients before you go." },
    placeHints: ["uraeok"],
    chipFollowups: [{ ko: "다른 분위기", en: "Different vibe" }, { ko: "더 가까운 데", en: "Closer option" }, { ko: "예산은 어때?", en: "Budget check" }],
  },
  {
    id: "sea-muslim-student-budget-1",
    characterId: "maya",
    segmentIds: ["sea-muslim-student"],
    intents: ["budget"],
    tags: ["budget", "sea-muslim-student", "maya"],
    text: { ko: "지갑 생각이면 광장시장부터. 식사 제약을 먼저 챙기는 기준으로 가격은 매장마다 다르니 메뉴판 기준으로만 말해 줄게.", en: "On a budget, start with Gwangjang Market. leading with dining constraints the way Maya does I will not invent prices—use the menu you see." },
    placeHints: ["gwangjang"],
    chipFollowups: [{ ko: "더 싸게", en: "Cheaper still" }, { ko: "배부르게", en: "More filling" }, { ko: "걸어서 갈 수 있게", en: "Walkable" }],
  },
  {
    id: "sea-muslim-student-budget-2",
    characterId: "maya",
    segmentIds: ["sea-muslim-student"],
    intents: ["budget"],
    tags: ["budget", "sea-muslim-student", "maya"],
    text: { ko: "지갑 생각이면 무학동 닭집부터. 식사 제약을 먼저 챙기는 기준으로 가격은 매장마다 다르니 메뉴판 기준으로만 말해 줄게.", en: "On a budget, start with Muhak chicken spot. leading with dining constraints the way Maya does I will not invent prices—use the menu you see." },
    placeHints: ["muhak-dak"],
    chipFollowups: [{ ko: "더 싸게", en: "Cheaper still" }, { ko: "배부르게", en: "More filling" }, { ko: "걸어서 갈 수 있게", en: "Walkable" }],
  },
  {
    id: "sea-muslim-student-night-1",
    characterId: "maya",
    segmentIds: ["sea-muslim-student"],
    intents: ["night"],
    tags: ["night", "sea-muslim-student", "maya"],
    text: { ko: "늦은 시간이면 마야는 을지로 노가리를 먼저 떠올려. 식사 제약을 먼저 챙기는 기준으로 너무 늦으면 영업 마감만 확인하고 가자.", en: "For a late hour, Maya leans Euljiro nogari alley. leading with dining constraints the way Maya does Confirm closing time if it is already late." },
    placeHints: ["euljiro-nogari"],
    chipFollowups: [{ ko: "야식 가볍게", en: "Lighter late bite" }, { ko: "산책으로 바꿀까", en: "Switch to a walk" }, { ko: "다른 밤 코스", en: "Another night pick" }],
  },
  {
    id: "sea-muslim-student-night-2",
    characterId: "maya",
    segmentIds: ["sea-muslim-student"],
    intents: ["night"],
    tags: ["night", "sea-muslim-student", "maya"],
    text: { ko: "늦은 시간이면 마야는 낙산공원를 먼저 떠올려. 식사 제약을 먼저 챙기는 기준으로 너무 늦으면 영업 마감만 확인하고 가자.", en: "For a late hour, Maya leans Naksan Park. leading with dining constraints the way Maya does Confirm closing time if it is already late." },
    placeHints: ["naksan"],
    chipFollowups: [{ ko: "야식 가볍게", en: "Lighter late bite" }, { ko: "산책으로 바꿀까", en: "Switch to a walk" }, { ko: "다른 밤 코스", en: "Another night pick" }],
  },
  {
    id: "sea-muslim-student-followup-1",
    characterId: "maya",
    segmentIds: ["sea-muslim-student"],
    intents: ["followup"],
    tags: ["followup", "sea-muslim-student"],
    text: { ko: "좋아. 그다음으로는 진주집를 이어서 볼까, 아니면 조건을 바꿀까?", en: "Nice. Next we can stay with Jinju-jip, or change the constraint." },
    placeHints: ["jinjujip"],
    chipFollowups: [{ ko: "여기로 갈게", en: "I will go here" }, { ko: "다른 후보", en: "Another option" }, { ko: "조건 바꾸기", en: "Change filters" }],
  },
  {
    id: "sea-family-halal-1",
    characterId: "maya",
    segmentIds: ["sea-family"],
    intents: ["halal"],
    tags: ["halal", "sea-family", "maya"],
    text: { ko: "돼지고기 빼는 흐름이면 이태원 케밥를 먼저 볼게. 할랄 인증·조리 도구·알코올은 별도 확인이 필요해.", en: "For a pork-free path, I look at Itaewon kebab first. Halal certification, utensils, and alcohol need separate checks." },
    placeHints: ["itaewon-kebab"],
    chipFollowups: [{ ko: "다른 무돼지고기", en: "Another no-pork" }, { ko: "야식도 괜찮아?", en: "Late-night OK?" }, { ko: "채식에 가깝게", en: "Closer to veg" }],
  },
  {
    id: "sea-family-food-1",
    characterId: "maya",
    segmentIds: ["sea-family"],
    intents: ["food"],
    tags: ["food", "sea-family", "maya"],
    text: { ko: "마야 기준으로 지금 배고프면 진주집 쪽이 맞아. 식사 제약을 먼저 챙기는 기준으로 재료·영업은 방문 전에 한 번만 확인해 줘.", en: "With Maya's taste, Jinju-jip fits a hungry turn. leading with dining constraints the way Maya does Double-check hours and ingredients before you go." },
    placeHints: ["jinjujip"],
    chipFollowups: [{ ko: "다른 분위기", en: "Different vibe" }, { ko: "더 가까운 데", en: "Closer option" }, { ko: "예산은 어때?", en: "Budget check" }],
  },
  {
    id: "sea-family-food-2",
    characterId: "maya",
    segmentIds: ["sea-family"],
    intents: ["food"],
    tags: ["food", "sea-family", "maya"],
    text: { ko: "마야 기준으로 지금 배고프면 을지로 우래옥 쪽이 맞아. 식사 제약을 먼저 챙기는 기준으로 재료·영업은 방문 전에 한 번만 확인해 줘.", en: "With Maya's taste, Uraeok fits a hungry turn. leading with dining constraints the way Maya does Double-check hours and ingredients before you go." },
    placeHints: ["uraeok"],
    chipFollowups: [{ ko: "다른 분위기", en: "Different vibe" }, { ko: "더 가까운 데", en: "Closer option" }, { ko: "예산은 어때?", en: "Budget check" }],
  },
  {
    id: "sea-family-group-1",
    characterId: "maya",
    segmentIds: ["sea-family"],
    intents: ["group"],
    tags: ["group", "sea-family", "maya"],
    text: { ko: "여럿이라면 광장시장처럼 나눠 먹기 쉬운 쪽이 편해. 식사 제약을 먼저 챙기는 기준으로", en: "For a small group, shareable spots like Gwangjang Market are easier. leading with dining constraints the way Maya does" },
    placeHints: ["gwangjang"],
    chipFollowups: [{ ko: "맵기 낮게", en: "Milder spice" }, { ko: "아이 배려", en: "Kid-friendly" }, { ko: "예약 필요할까?", en: "Need a booking?" }],
  },
  {
    id: "sea-family-group-2",
    characterId: "maya",
    segmentIds: ["sea-family"],
    intents: ["group"],
    tags: ["group", "sea-family", "maya"],
    text: { ko: "여럿이라면 을지로 우래옥처럼 나눠 먹기 쉬운 쪽이 편해. 식사 제약을 먼저 챙기는 기준으로", en: "For a small group, shareable spots like Uraeok are easier. leading with dining constraints the way Maya does" },
    placeHints: ["uraeok"],
    chipFollowups: [{ ko: "맵기 낮게", en: "Milder spice" }, { ko: "아이 배려", en: "Kid-friendly" }, { ko: "예약 필요할까?", en: "Need a booking?" }],
  },
  {
    id: "sea-family-followup-1",
    characterId: "maya",
    segmentIds: ["sea-family"],
    intents: ["followup"],
    tags: ["followup", "sea-family"],
    text: { ko: "좋아. 그다음으로는 진주집를 이어서 볼까, 아니면 조건을 바꿀까?", en: "Nice. Next we can stay with Jinju-jip, or change the constraint." },
    placeHints: ["jinjujip"],
    chipFollowups: [{ ko: "여기로 갈게", en: "I will go here" }, { ko: "다른 후보", en: "Another option" }, { ko: "조건 바꾸기", en: "Change filters" }],
  },
  {
    id: "sea-worker-food-1",
    characterId: "tom",
    segmentIds: ["sea-worker"],
    intents: ["food"],
    tags: ["food", "sea-worker", "tom"],
    text: { ko: "톰 기준으로 지금 배고프면 진주집 쪽이 맞아. 값어치와 배부름을 먼저 보는 기준으로 재료·영업은 방문 전에 한 번만 확인해 줘.", en: "With Tom's taste, Jinju-jip fits a hungry turn. favoring value and fullness the way Tom ranks Double-check hours and ingredients before you go." },
    placeHints: ["jinjujip"],
    chipFollowups: [{ ko: "다른 분위기", en: "Different vibe" }, { ko: "더 가까운 데", en: "Closer option" }, { ko: "예산은 어때?", en: "Budget check" }],
  },
  {
    id: "sea-worker-food-2",
    characterId: "tom",
    segmentIds: ["sea-worker"],
    intents: ["food"],
    tags: ["food", "sea-worker", "tom"],
    text: { ko: "톰 기준으로 지금 배고프면 을지로 우래옥 쪽이 맞아. 값어치와 배부름을 먼저 보는 기준으로 재료·영업은 방문 전에 한 번만 확인해 줘.", en: "With Tom's taste, Uraeok fits a hungry turn. favoring value and fullness the way Tom ranks Double-check hours and ingredients before you go." },
    placeHints: ["uraeok"],
    chipFollowups: [{ ko: "다른 분위기", en: "Different vibe" }, { ko: "더 가까운 데", en: "Closer option" }, { ko: "예산은 어때?", en: "Budget check" }],
  },
  {
    id: "sea-worker-night-1",
    characterId: "tom",
    segmentIds: ["sea-worker"],
    intents: ["night"],
    tags: ["night", "sea-worker", "tom"],
    text: { ko: "늦은 시간이면 톰는 을지로 노가리를 먼저 떠올려. 값어치와 배부름을 먼저 보는 기준으로 너무 늦으면 영업 마감만 확인하고 가자.", en: "For a late hour, Tom leans Euljiro nogari alley. favoring value and fullness the way Tom ranks Confirm closing time if it is already late." },
    placeHints: ["euljiro-nogari"],
    chipFollowups: [{ ko: "야식 가볍게", en: "Lighter late bite" }, { ko: "산책으로 바꿀까", en: "Switch to a walk" }, { ko: "다른 밤 코스", en: "Another night pick" }],
  },
  {
    id: "sea-worker-night-2",
    characterId: "tom",
    segmentIds: ["sea-worker"],
    intents: ["night"],
    tags: ["night", "sea-worker", "tom"],
    text: { ko: "늦은 시간이면 톰는 낙산공원를 먼저 떠올려. 값어치와 배부름을 먼저 보는 기준으로 너무 늦으면 영업 마감만 확인하고 가자.", en: "For a late hour, Tom leans Naksan Park. favoring value and fullness the way Tom ranks Confirm closing time if it is already late." },
    placeHints: ["naksan"],
    chipFollowups: [{ ko: "야식 가볍게", en: "Lighter late bite" }, { ko: "산책으로 바꿀까", en: "Switch to a walk" }, { ko: "다른 밤 코스", en: "Another night pick" }],
  },
  {
    id: "sea-worker-budget-1",
    characterId: "tom",
    segmentIds: ["sea-worker"],
    intents: ["budget"],
    tags: ["budget", "sea-worker", "tom"],
    text: { ko: "지갑 생각이면 광장시장부터. 값어치와 배부름을 먼저 보는 기준으로 가격은 매장마다 다르니 메뉴판 기준으로만 말해 줄게.", en: "On a budget, start with Gwangjang Market. favoring value and fullness the way Tom ranks I will not invent prices—use the menu you see." },
    placeHints: ["gwangjang"],
    chipFollowups: [{ ko: "더 싸게", en: "Cheaper still" }, { ko: "배부르게", en: "More filling" }, { ko: "걸어서 갈 수 있게", en: "Walkable" }],
  },
  {
    id: "sea-worker-budget-2",
    characterId: "tom",
    segmentIds: ["sea-worker"],
    intents: ["budget"],
    tags: ["budget", "sea-worker", "tom"],
    text: { ko: "지갑 생각이면 무학동 닭집부터. 값어치와 배부름을 먼저 보는 기준으로 가격은 매장마다 다르니 메뉴판 기준으로만 말해 줄게.", en: "On a budget, start with Muhak chicken spot. favoring value and fullness the way Tom ranks I will not invent prices—use the menu you see." },
    placeHints: ["muhak-dak"],
    chipFollowups: [{ ko: "더 싸게", en: "Cheaper still" }, { ko: "배부르게", en: "More filling" }, { ko: "걸어서 갈 수 있게", en: "Walkable" }],
  },
  {
    id: "sea-worker-followup-1",
    characterId: "tom",
    segmentIds: ["sea-worker"],
    intents: ["followup"],
    tags: ["followup", "sea-worker"],
    text: { ko: "좋아. 그다음으로는 진주집를 이어서 볼까, 아니면 조건을 바꿀까?", en: "Nice. Next we can stay with Jinju-jip, or change the constraint." },
    placeHints: ["jinjujip"],
    chipFollowups: [{ ko: "여기로 갈게", en: "I will go here" }, { ko: "다른 후보", en: "Another option" }, { ko: "조건 바꾸기", en: "Change filters" }],
  },
  {
    id: "sea-wh-food-1",
    characterId: "nuri",
    segmentIds: ["sea-wh"],
    intents: ["food"],
    tags: ["food", "sea-wh", "nuri"],
    text: { ko: "누리 기준으로 지금 배고프면 진주집 쪽이 맞아. 걸어갈 수 있는 동네 동선 기준으로 재료·영업은 방문 전에 한 번만 확인해 줘.", en: "With Nuri's taste, Jinju-jip fits a hungry turn. using walkable neighborhood logic like Nuri Double-check hours and ingredients before you go." },
    placeHints: ["jinjujip"],
    chipFollowups: [{ ko: "다른 분위기", en: "Different vibe" }, { ko: "더 가까운 데", en: "Closer option" }, { ko: "예산은 어때?", en: "Budget check" }],
  },
  {
    id: "sea-wh-food-2",
    characterId: "nuri",
    segmentIds: ["sea-wh"],
    intents: ["food"],
    tags: ["food", "sea-wh", "nuri"],
    text: { ko: "누리 기준으로 지금 배고프면 을지로 우래옥 쪽이 맞아. 걸어갈 수 있는 동네 동선 기준으로 재료·영업은 방문 전에 한 번만 확인해 줘.", en: "With Nuri's taste, Uraeok fits a hungry turn. using walkable neighborhood logic like Nuri Double-check hours and ingredients before you go." },
    placeHints: ["uraeok"],
    chipFollowups: [{ ko: "다른 분위기", en: "Different vibe" }, { ko: "더 가까운 데", en: "Closer option" }, { ko: "예산은 어때?", en: "Budget check" }],
  },
  {
    id: "sea-wh-walk-1",
    characterId: "nuri",
    segmentIds: ["sea-wh"],
    intents: ["walk"],
    tags: ["walk", "sea-wh", "nuri"],
    text: { ko: "걷기 좋은 코스로는 서울숲가 무난해. 걸어갈 수 있는 동네 동선 기준으로 비 오면 실내로 바로 바꿔 줄게.", en: "For a walkable stretch, Seoul Forest is steady. using walkable neighborhood logic like Nuri If it rains we switch indoors." },
    placeHints: ["seoul-forest"],
    chipFollowups: [{ ko: "더 조용하게", en: "Quieter path" }, { ko: "짧게만", en: "Keep it short" }, { ko: "카페로 이어서", en: "Then a cafe" }],
  },
  {
    id: "sea-wh-walk-2",
    characterId: "nuri",
    segmentIds: ["sea-wh"],
    intents: ["walk"],
    tags: ["walk", "sea-wh", "nuri"],
    text: { ko: "걷기 좋은 코스로는 뚝섬한강공원가 무난해. 걸어갈 수 있는 동네 동선 기준으로 비 오면 실내로 바로 바꿔 줄게.", en: "For a walkable stretch, Ttukseom Hangang Park is steady. using walkable neighborhood logic like Nuri If it rains we switch indoors." },
    placeHints: ["ttukseom"],
    chipFollowups: [{ ko: "더 조용하게", en: "Quieter path" }, { ko: "짧게만", en: "Keep it short" }, { ko: "카페로 이어서", en: "Then a cafe" }],
  },
  {
    id: "sea-wh-budget-1",
    characterId: "nuri",
    segmentIds: ["sea-wh"],
    intents: ["budget"],
    tags: ["budget", "sea-wh", "nuri"],
    text: { ko: "지갑 생각이면 광장시장부터. 걸어갈 수 있는 동네 동선 기준으로 가격은 매장마다 다르니 메뉴판 기준으로만 말해 줄게.", en: "On a budget, start with Gwangjang Market. using walkable neighborhood logic like Nuri I will not invent prices—use the menu you see." },
    placeHints: ["gwangjang"],
    chipFollowups: [{ ko: "더 싸게", en: "Cheaper still" }, { ko: "배부르게", en: "More filling" }, { ko: "걸어서 갈 수 있게", en: "Walkable" }],
  },
  {
    id: "sea-wh-budget-2",
    characterId: "nuri",
    segmentIds: ["sea-wh"],
    intents: ["budget"],
    tags: ["budget", "sea-wh", "nuri"],
    text: { ko: "지갑 생각이면 무학동 닭집부터. 걸어갈 수 있는 동네 동선 기준으로 가격은 매장마다 다르니 메뉴판 기준으로만 말해 줄게.", en: "On a budget, start with Muhak chicken spot. using walkable neighborhood logic like Nuri I will not invent prices—use the menu you see." },
    placeHints: ["muhak-dak"],
    chipFollowups: [{ ko: "더 싸게", en: "Cheaper still" }, { ko: "배부르게", en: "More filling" }, { ko: "걸어서 갈 수 있게", en: "Walkable" }],
  },
  {
    id: "sea-wh-night-1",
    characterId: "nuri",
    segmentIds: ["sea-wh"],
    intents: ["night"],
    tags: ["night", "sea-wh", "nuri"],
    text: { ko: "늦은 시간이면 누리는 을지로 노가리를 먼저 떠올려. 걸어갈 수 있는 동네 동선 기준으로 너무 늦으면 영업 마감만 확인하고 가자.", en: "For a late hour, Nuri leans Euljiro nogari alley. using walkable neighborhood logic like Nuri Confirm closing time if it is already late." },
    placeHints: ["euljiro-nogari"],
    chipFollowups: [{ ko: "야식 가볍게", en: "Lighter late bite" }, { ko: "산책으로 바꿀까", en: "Switch to a walk" }, { ko: "다른 밤 코스", en: "Another night pick" }],
  },
  {
    id: "sea-wh-night-2",
    characterId: "nuri",
    segmentIds: ["sea-wh"],
    intents: ["night"],
    tags: ["night", "sea-wh", "nuri"],
    text: { ko: "늦은 시간이면 누리는 낙산공원를 먼저 떠올려. 걸어갈 수 있는 동네 동선 기준으로 너무 늦으면 영업 마감만 확인하고 가자.", en: "For a late hour, Nuri leans Naksan Park. using walkable neighborhood logic like Nuri Confirm closing time if it is already late." },
    placeHints: ["naksan"],
    chipFollowups: [{ ko: "야식 가볍게", en: "Lighter late bite" }, { ko: "산책으로 바꿀까", en: "Switch to a walk" }, { ko: "다른 밤 코스", en: "Another night pick" }],
  },
  {
    id: "sea-wh-followup-1",
    characterId: "nuri",
    segmentIds: ["sea-wh"],
    intents: ["followup"],
    tags: ["followup", "sea-wh"],
    text: { ko: "좋아. 그다음으로는 진주집를 이어서 볼까, 아니면 조건을 바꿀까?", en: "Nice. Next we can stay with Jinju-jip, or change the constraint." },
    placeHints: ["jinjujip"],
    chipFollowups: [{ ko: "여기로 갈게", en: "I will go here" }, { ko: "다른 후보", en: "Another option" }, { ko: "조건 바꾸기", en: "Change filters" }],
  },
  {
    id: "en-backpacker-budget-1",
    characterId: "tom",
    segmentIds: ["en-backpacker"],
    intents: ["budget"],
    tags: ["budget", "en-backpacker", "tom"],
    text: { ko: "지갑 생각이면 광장시장부터. 값어치와 배부름을 먼저 보는 기준으로 가격은 매장마다 다르니 메뉴판 기준으로만 말해 줄게.", en: "On a budget, start with Gwangjang Market. favoring value and fullness the way Tom ranks I will not invent prices—use the menu you see." },
    placeHints: ["gwangjang"],
    chipFollowups: [{ ko: "더 싸게", en: "Cheaper still" }, { ko: "배부르게", en: "More filling" }, { ko: "걸어서 갈 수 있게", en: "Walkable" }],
  },
  {
    id: "en-backpacker-budget-2",
    characterId: "tom",
    segmentIds: ["en-backpacker"],
    intents: ["budget"],
    tags: ["budget", "en-backpacker", "tom"],
    text: { ko: "지갑 생각이면 무학동 닭집부터. 값어치와 배부름을 먼저 보는 기준으로 가격은 매장마다 다르니 메뉴판 기준으로만 말해 줄게.", en: "On a budget, start with Muhak chicken spot. favoring value and fullness the way Tom ranks I will not invent prices—use the menu you see." },
    placeHints: ["muhak-dak"],
    chipFollowups: [{ ko: "더 싸게", en: "Cheaper still" }, { ko: "배부르게", en: "More filling" }, { ko: "걸어서 갈 수 있게", en: "Walkable" }],
  },
  {
    id: "en-backpacker-food-1",
    characterId: "tom",
    segmentIds: ["en-backpacker"],
    intents: ["food"],
    tags: ["food", "en-backpacker", "tom"],
    text: { ko: "톰 기준으로 지금 배고프면 진주집 쪽이 맞아. 값어치와 배부름을 먼저 보는 기준으로 재료·영업은 방문 전에 한 번만 확인해 줘.", en: "With Tom's taste, Jinju-jip fits a hungry turn. favoring value and fullness the way Tom ranks Double-check hours and ingredients before you go." },
    placeHints: ["jinjujip"],
    chipFollowups: [{ ko: "다른 분위기", en: "Different vibe" }, { ko: "더 가까운 데", en: "Closer option" }, { ko: "예산은 어때?", en: "Budget check" }],
  },
  {
    id: "en-backpacker-food-2",
    characterId: "tom",
    segmentIds: ["en-backpacker"],
    intents: ["food"],
    tags: ["food", "en-backpacker", "tom"],
    text: { ko: "톰 기준으로 지금 배고프면 을지로 우래옥 쪽이 맞아. 값어치와 배부름을 먼저 보는 기준으로 재료·영업은 방문 전에 한 번만 확인해 줘.", en: "With Tom's taste, Uraeok fits a hungry turn. favoring value and fullness the way Tom ranks Double-check hours and ingredients before you go." },
    placeHints: ["uraeok"],
    chipFollowups: [{ ko: "다른 분위기", en: "Different vibe" }, { ko: "더 가까운 데", en: "Closer option" }, { ko: "예산은 어때?", en: "Budget check" }],
  },
  {
    id: "en-backpacker-walk-1",
    characterId: "tom",
    segmentIds: ["en-backpacker"],
    intents: ["walk"],
    tags: ["walk", "en-backpacker", "tom"],
    text: { ko: "걷기 좋은 코스로는 서울숲가 무난해. 값어치와 배부름을 먼저 보는 기준으로 비 오면 실내로 바로 바꿔 줄게.", en: "For a walkable stretch, Seoul Forest is steady. favoring value and fullness the way Tom ranks If it rains we switch indoors." },
    placeHints: ["seoul-forest"],
    chipFollowups: [{ ko: "더 조용하게", en: "Quieter path" }, { ko: "짧게만", en: "Keep it short" }, { ko: "카페로 이어서", en: "Then a cafe" }],
  },
  {
    id: "en-backpacker-walk-2",
    characterId: "tom",
    segmentIds: ["en-backpacker"],
    intents: ["walk"],
    tags: ["walk", "en-backpacker", "tom"],
    text: { ko: "걷기 좋은 코스로는 뚝섬한강공원가 무난해. 값어치와 배부름을 먼저 보는 기준으로 비 오면 실내로 바로 바꿔 줄게.", en: "For a walkable stretch, Ttukseom Hangang Park is steady. favoring value and fullness the way Tom ranks If it rains we switch indoors." },
    placeHints: ["ttukseom"],
    chipFollowups: [{ ko: "더 조용하게", en: "Quieter path" }, { ko: "짧게만", en: "Keep it short" }, { ko: "카페로 이어서", en: "Then a cafe" }],
  },
  {
    id: "en-backpacker-followup-1",
    characterId: "tom",
    segmentIds: ["en-backpacker"],
    intents: ["followup"],
    tags: ["followup", "en-backpacker"],
    text: { ko: "좋아. 그다음으로는 진주집를 이어서 볼까, 아니면 조건을 바꿀까?", en: "Nice. Next we can stay with Jinju-jip, or change the constraint." },
    placeHints: ["jinjujip"],
    chipFollowups: [{ ko: "여기로 갈게", en: "I will go here" }, { ko: "다른 후보", en: "Another option" }, { ko: "조건 바꾸기", en: "Change filters" }],
  },
  {
    id: "en-worker-food-1",
    characterId: "nuri",
    segmentIds: ["en-worker"],
    intents: ["food"],
    tags: ["food", "en-worker", "nuri"],
    text: { ko: "누리 기준으로 지금 배고프면 진주집 쪽이 맞아. 걸어갈 수 있는 동네 동선 기준으로 재료·영업은 방문 전에 한 번만 확인해 줘.", en: "With Nuri's taste, Jinju-jip fits a hungry turn. using walkable neighborhood logic like Nuri Double-check hours and ingredients before you go." },
    placeHints: ["jinjujip"],
    chipFollowups: [{ ko: "다른 분위기", en: "Different vibe" }, { ko: "더 가까운 데", en: "Closer option" }, { ko: "예산은 어때?", en: "Budget check" }],
  },
  {
    id: "en-worker-food-2",
    characterId: "nuri",
    segmentIds: ["en-worker"],
    intents: ["food"],
    tags: ["food", "en-worker", "nuri"],
    text: { ko: "누리 기준으로 지금 배고프면 을지로 우래옥 쪽이 맞아. 걸어갈 수 있는 동네 동선 기준으로 재료·영업은 방문 전에 한 번만 확인해 줘.", en: "With Nuri's taste, Uraeok fits a hungry turn. using walkable neighborhood logic like Nuri Double-check hours and ingredients before you go." },
    placeHints: ["uraeok"],
    chipFollowups: [{ ko: "다른 분위기", en: "Different vibe" }, { ko: "더 가까운 데", en: "Closer option" }, { ko: "예산은 어때?", en: "Budget check" }],
  },
  {
    id: "en-worker-night-1",
    characterId: "nuri",
    segmentIds: ["en-worker"],
    intents: ["night"],
    tags: ["night", "en-worker", "nuri"],
    text: { ko: "늦은 시간이면 누리는 을지로 노가리를 먼저 떠올려. 걸어갈 수 있는 동네 동선 기준으로 너무 늦으면 영업 마감만 확인하고 가자.", en: "For a late hour, Nuri leans Euljiro nogari alley. using walkable neighborhood logic like Nuri Confirm closing time if it is already late." },
    placeHints: ["euljiro-nogari"],
    chipFollowups: [{ ko: "야식 가볍게", en: "Lighter late bite" }, { ko: "산책으로 바꿀까", en: "Switch to a walk" }, { ko: "다른 밤 코스", en: "Another night pick" }],
  },
  {
    id: "en-worker-night-2",
    characterId: "nuri",
    segmentIds: ["en-worker"],
    intents: ["night"],
    tags: ["night", "en-worker", "nuri"],
    text: { ko: "늦은 시간이면 누리는 낙산공원를 먼저 떠올려. 걸어갈 수 있는 동네 동선 기준으로 너무 늦으면 영업 마감만 확인하고 가자.", en: "For a late hour, Nuri leans Naksan Park. using walkable neighborhood logic like Nuri Confirm closing time if it is already late." },
    placeHints: ["naksan"],
    chipFollowups: [{ ko: "야식 가볍게", en: "Lighter late bite" }, { ko: "산책으로 바꿀까", en: "Switch to a walk" }, { ko: "다른 밤 코스", en: "Another night pick" }],
  },
  {
    id: "en-worker-walk-1",
    characterId: "nuri",
    segmentIds: ["en-worker"],
    intents: ["walk"],
    tags: ["walk", "en-worker", "nuri"],
    text: { ko: "걷기 좋은 코스로는 서울숲가 무난해. 걸어갈 수 있는 동네 동선 기준으로 비 오면 실내로 바로 바꿔 줄게.", en: "For a walkable stretch, Seoul Forest is steady. using walkable neighborhood logic like Nuri If it rains we switch indoors." },
    placeHints: ["seoul-forest"],
    chipFollowups: [{ ko: "더 조용하게", en: "Quieter path" }, { ko: "짧게만", en: "Keep it short" }, { ko: "카페로 이어서", en: "Then a cafe" }],
  },
  {
    id: "en-worker-walk-2",
    characterId: "nuri",
    segmentIds: ["en-worker"],
    intents: ["walk"],
    tags: ["walk", "en-worker", "nuri"],
    text: { ko: "걷기 좋은 코스로는 뚝섬한강공원가 무난해. 걸어갈 수 있는 동네 동선 기준으로 비 오면 실내로 바로 바꿔 줄게.", en: "For a walkable stretch, Ttukseom Hangang Park is steady. using walkable neighborhood logic like Nuri If it rains we switch indoors." },
    placeHints: ["ttukseom"],
    chipFollowups: [{ ko: "더 조용하게", en: "Quieter path" }, { ko: "짧게만", en: "Keep it short" }, { ko: "카페로 이어서", en: "Then a cafe" }],
  },
  {
    id: "en-worker-followup-1",
    characterId: "nuri",
    segmentIds: ["en-worker"],
    intents: ["followup"],
    tags: ["followup", "en-worker"],
    text: { ko: "좋아. 그다음으로는 진주집를 이어서 볼까, 아니면 조건을 바꿀까?", en: "Nice. Next we can stay with Jinju-jip, or change the constraint." },
    placeHints: ["jinjujip"],
    chipFollowups: [{ ko: "여기로 갈게", en: "I will go here" }, { ko: "다른 후보", en: "Another option" }, { ko: "조건 바꾸기", en: "Change filters" }],
  },
  {
    id: "eu-backpacker-budget-1",
    characterId: "tom",
    segmentIds: ["eu-backpacker"],
    intents: ["budget"],
    tags: ["budget", "eu-backpacker", "tom"],
    text: { ko: "지갑 생각이면 광장시장부터. 값어치와 배부름을 먼저 보는 기준으로 가격은 매장마다 다르니 메뉴판 기준으로만 말해 줄게.", en: "On a budget, start with Gwangjang Market. favoring value and fullness the way Tom ranks I will not invent prices—use the menu you see." },
    placeHints: ["gwangjang"],
    chipFollowups: [{ ko: "더 싸게", en: "Cheaper still" }, { ko: "배부르게", en: "More filling" }, { ko: "걸어서 갈 수 있게", en: "Walkable" }],
  },
  {
    id: "eu-backpacker-budget-2",
    characterId: "tom",
    segmentIds: ["eu-backpacker"],
    intents: ["budget"],
    tags: ["budget", "eu-backpacker", "tom"],
    text: { ko: "지갑 생각이면 무학동 닭집부터. 값어치와 배부름을 먼저 보는 기준으로 가격은 매장마다 다르니 메뉴판 기준으로만 말해 줄게.", en: "On a budget, start with Muhak chicken spot. favoring value and fullness the way Tom ranks I will not invent prices—use the menu you see." },
    placeHints: ["muhak-dak"],
    chipFollowups: [{ ko: "더 싸게", en: "Cheaper still" }, { ko: "배부르게", en: "More filling" }, { ko: "걸어서 갈 수 있게", en: "Walkable" }],
  },
  {
    id: "eu-backpacker-food-1",
    characterId: "tom",
    segmentIds: ["eu-backpacker"],
    intents: ["food"],
    tags: ["food", "eu-backpacker", "tom"],
    text: { ko: "톰 기준으로 지금 배고프면 진주집 쪽이 맞아. 값어치와 배부름을 먼저 보는 기준으로 재료·영업은 방문 전에 한 번만 확인해 줘.", en: "With Tom's taste, Jinju-jip fits a hungry turn. favoring value and fullness the way Tom ranks Double-check hours and ingredients before you go." },
    placeHints: ["jinjujip"],
    chipFollowups: [{ ko: "다른 분위기", en: "Different vibe" }, { ko: "더 가까운 데", en: "Closer option" }, { ko: "예산은 어때?", en: "Budget check" }],
  },
  {
    id: "eu-backpacker-food-2",
    characterId: "tom",
    segmentIds: ["eu-backpacker"],
    intents: ["food"],
    tags: ["food", "eu-backpacker", "tom"],
    text: { ko: "톰 기준으로 지금 배고프면 을지로 우래옥 쪽이 맞아. 값어치와 배부름을 먼저 보는 기준으로 재료·영업은 방문 전에 한 번만 확인해 줘.", en: "With Tom's taste, Uraeok fits a hungry turn. favoring value and fullness the way Tom ranks Double-check hours and ingredients before you go." },
    placeHints: ["uraeok"],
    chipFollowups: [{ ko: "다른 분위기", en: "Different vibe" }, { ko: "더 가까운 데", en: "Closer option" }, { ko: "예산은 어때?", en: "Budget check" }],
  },
  {
    id: "eu-backpacker-cafe-1",
    characterId: "tom",
    segmentIds: ["eu-backpacker"],
    intents: ["cafe"],
    tags: ["cafe", "eu-backpacker", "tom"],
    text: { ko: "잠깐 쉬려면 성수 카페 거리가 무난해. 값어치와 배부름을 먼저 보는 기준으로 웨이팅은 현장 기준으로만 봐 줘.", en: "For a short pause, Seongsu cafe streets works. favoring value and fullness the way Tom ranks Treat wait times as on-site only." },
    placeHints: ["seongsu-onion"],
    chipFollowups: [{ ko: "디저트", en: "Dessert" }, { ko: "작업하기 좋게", en: "Good for laptop" }, { ko: "근처 산책", en: "Nearby walk" }],
  },
  {
    id: "eu-backpacker-cafe-2",
    characterId: "tom",
    segmentIds: ["eu-backpacker"],
    intents: ["cafe"],
    tags: ["cafe", "eu-backpacker", "tom"],
    text: { ko: "잠깐 쉬려면 커먼그라운드가 무난해. 값어치와 배부름을 먼저 보는 기준으로 웨이팅은 현장 기준으로만 봐 줘.", en: "For a short pause, Common Ground works. favoring value and fullness the way Tom ranks Treat wait times as on-site only." },
    placeHints: ["common-ground"],
    chipFollowups: [{ ko: "디저트", en: "Dessert" }, { ko: "작업하기 좋게", en: "Good for laptop" }, { ko: "근처 산책", en: "Nearby walk" }],
  },
  {
    id: "eu-backpacker-followup-1",
    characterId: "tom",
    segmentIds: ["eu-backpacker"],
    intents: ["followup"],
    tags: ["followup", "eu-backpacker"],
    text: { ko: "좋아. 그다음으로는 진주집를 이어서 볼까, 아니면 조건을 바꿀까?", en: "Nice. Next we can stay with Jinju-jip, or change the constraint." },
    placeHints: ["jinjujip"],
    chipFollowups: [{ ko: "여기로 갈게", en: "I will go here" }, { ko: "다른 후보", en: "Another option" }, { ko: "조건 바꾸기", en: "Change filters" }],
  },
  {
    id: "eu-couple-walk-1",
    characterId: "dal",
    segmentIds: ["eu-couple"],
    intents: ["walk"],
    tags: ["walk", "eu-couple", "dal"],
    text: { ko: "걷기 좋은 코스로는 서울숲가 무난해. 속도·밀도·편안함을 보는 기준으로 비 오면 실내로 바로 바꿔 줄게.", en: "For a walkable stretch, Seoul Forest is steady. watching pace, density, and ease like Dal If it rains we switch indoors." },
    placeHints: ["seoul-forest"],
    chipFollowups: [{ ko: "더 조용하게", en: "Quieter path" }, { ko: "짧게만", en: "Keep it short" }, { ko: "카페로 이어서", en: "Then a cafe" }],
  },
  {
    id: "eu-couple-walk-2",
    characterId: "dal",
    segmentIds: ["eu-couple"],
    intents: ["walk"],
    tags: ["walk", "eu-couple", "dal"],
    text: { ko: "걷기 좋은 코스로는 뚝섬한강공원가 무난해. 속도·밀도·편안함을 보는 기준으로 비 오면 실내로 바로 바꿔 줄게.", en: "For a walkable stretch, Ttukseom Hangang Park is steady. watching pace, density, and ease like Dal If it rains we switch indoors." },
    placeHints: ["ttukseom"],
    chipFollowups: [{ ko: "더 조용하게", en: "Quieter path" }, { ko: "짧게만", en: "Keep it short" }, { ko: "카페로 이어서", en: "Then a cafe" }],
  },
  {
    id: "eu-couple-cafe-1",
    characterId: "dal",
    segmentIds: ["eu-couple"],
    intents: ["cafe"],
    tags: ["cafe", "eu-couple", "dal"],
    text: { ko: "잠깐 쉬려면 성수 카페 거리가 무난해. 속도·밀도·편안함을 보는 기준으로 웨이팅은 현장 기준으로만 봐 줘.", en: "For a short pause, Seongsu cafe streets works. watching pace, density, and ease like Dal Treat wait times as on-site only." },
    placeHints: ["seongsu-onion"],
    chipFollowups: [{ ko: "디저트", en: "Dessert" }, { ko: "작업하기 좋게", en: "Good for laptop" }, { ko: "근처 산책", en: "Nearby walk" }],
  },
  {
    id: "eu-couple-cafe-2",
    characterId: "dal",
    segmentIds: ["eu-couple"],
    intents: ["cafe"],
    tags: ["cafe", "eu-couple", "dal"],
    text: { ko: "잠깐 쉬려면 커먼그라운드가 무난해. 속도·밀도·편안함을 보는 기준으로 웨이팅은 현장 기준으로만 봐 줘.", en: "For a short pause, Common Ground works. watching pace, density, and ease like Dal Treat wait times as on-site only." },
    placeHints: ["common-ground"],
    chipFollowups: [{ ko: "디저트", en: "Dessert" }, { ko: "작업하기 좋게", en: "Good for laptop" }, { ko: "근처 산책", en: "Nearby walk" }],
  },
  {
    id: "eu-couple-night-1",
    characterId: "dal",
    segmentIds: ["eu-couple"],
    intents: ["night"],
    tags: ["night", "eu-couple", "dal"],
    text: { ko: "늦은 시간이면 달는 을지로 노가리를 먼저 떠올려. 속도·밀도·편안함을 보는 기준으로 너무 늦으면 영업 마감만 확인하고 가자.", en: "For a late hour, Dal leans Euljiro nogari alley. watching pace, density, and ease like Dal Confirm closing time if it is already late." },
    placeHints: ["euljiro-nogari"],
    chipFollowups: [{ ko: "야식 가볍게", en: "Lighter late bite" }, { ko: "산책으로 바꿀까", en: "Switch to a walk" }, { ko: "다른 밤 코스", en: "Another night pick" }],
  },
  {
    id: "eu-couple-night-2",
    characterId: "dal",
    segmentIds: ["eu-couple"],
    intents: ["night"],
    tags: ["night", "eu-couple", "dal"],
    text: { ko: "늦은 시간이면 달는 낙산공원를 먼저 떠올려. 속도·밀도·편안함을 보는 기준으로 너무 늦으면 영업 마감만 확인하고 가자.", en: "For a late hour, Dal leans Naksan Park. watching pace, density, and ease like Dal Confirm closing time if it is already late." },
    placeHints: ["naksan"],
    chipFollowups: [{ ko: "야식 가볍게", en: "Lighter late bite" }, { ko: "산책으로 바꿀까", en: "Switch to a walk" }, { ko: "다른 밤 코스", en: "Another night pick" }],
  },
  {
    id: "eu-couple-food-1",
    characterId: "dal",
    segmentIds: ["eu-couple"],
    intents: ["food"],
    tags: ["food", "eu-couple", "dal"],
    text: { ko: "달 기준으로 지금 배고프면 진주집 쪽이 맞아. 속도·밀도·편안함을 보는 기준으로 재료·영업은 방문 전에 한 번만 확인해 줘.", en: "With Dal's taste, Jinju-jip fits a hungry turn. watching pace, density, and ease like Dal Double-check hours and ingredients before you go." },
    placeHints: ["jinjujip"],
    chipFollowups: [{ ko: "다른 분위기", en: "Different vibe" }, { ko: "더 가까운 데", en: "Closer option" }, { ko: "예산은 어때?", en: "Budget check" }],
  },
  {
    id: "eu-couple-food-2",
    characterId: "dal",
    segmentIds: ["eu-couple"],
    intents: ["food"],
    tags: ["food", "eu-couple", "dal"],
    text: { ko: "달 기준으로 지금 배고프면 을지로 우래옥 쪽이 맞아. 속도·밀도·편안함을 보는 기준으로 재료·영업은 방문 전에 한 번만 확인해 줘.", en: "With Dal's taste, Uraeok fits a hungry turn. watching pace, density, and ease like Dal Double-check hours and ingredients before you go." },
    placeHints: ["uraeok"],
    chipFollowups: [{ ko: "다른 분위기", en: "Different vibe" }, { ko: "더 가까운 데", en: "Closer option" }, { ko: "예산은 어때?", en: "Budget check" }],
  },
  {
    id: "eu-couple-followup-1",
    characterId: "dal",
    segmentIds: ["eu-couple"],
    intents: ["followup"],
    tags: ["followup", "eu-couple"],
    text: { ko: "좋아. 그다음으로는 진주집를 이어서 볼까, 아니면 조건을 바꿀까?", en: "Nice. Next we can stay with Jinju-jip, or change the constraint." },
    placeHints: ["jinjujip"],
    chipFollowups: [{ ko: "여기로 갈게", en: "I will go here" }, { ko: "다른 후보", en: "Another option" }, { ko: "조건 바꾸기", en: "Change filters" }],
  },
  {
    id: "in-it-vegetarian-1",
    characterId: "rina",
    segmentIds: ["in-it"],
    intents: ["vegetarian"],
    tags: ["vegetarian", "in-it", "rina"],
    text: { ko: "채식 쪽으로는 성수 카페 거리가 후보야. 육수·젓갈은 방문 전 확인이 필요하고, 비건을 보장하진 않아.", en: "For vegetarian-leaning picks, Seongsu cafe streets is on the list. Broth and fish sauce need checking; I never promise vegan." },
    placeHints: ["seongsu-onion"],
    chipFollowups: [{ ko: "덜 맵게", en: "Milder spice" }, { ko: "카페로", en: "Cafe instead" }, { ko: "다른 채식", en: "Another veg pick" }],
  },
  {
    id: "in-it-vegetarian-2",
    characterId: "rina",
    segmentIds: ["in-it"],
    intents: ["vegetarian"],
    tags: ["vegetarian", "in-it", "rina"],
    text: { ko: "채식 쪽으로는 이태원 케밥가 후보야. 육수·젓갈은 방문 전 확인이 필요하고, 비건을 보장하진 않아.", en: "For vegetarian-leaning picks, Itaewon kebab is on the list. Broth and fish sauce need checking; I never promise vegan." },
    placeHints: ["itaewon-kebab"],
    chipFollowups: [{ ko: "덜 맵게", en: "Milder spice" }, { ko: "카페로", en: "Cafe instead" }, { ko: "다른 채식", en: "Another veg pick" }],
  },
  {
    id: "in-it-food-1",
    characterId: "rina",
    segmentIds: ["in-it"],
    intents: ["food"],
    tags: ["food", "in-it", "rina"],
    text: { ko: "리나 기준으로 지금 배고프면 진주집 쪽이 맞아. 채식 가능 여부를 먼저 보는 기준으로 재료·영업은 방문 전에 한 번만 확인해 줘.", en: "With Rina's taste, Jinju-jip fits a hungry turn. checking vegetarian-friendliness first like Rina Double-check hours and ingredients before you go." },
    placeHints: ["jinjujip"],
    chipFollowups: [{ ko: "다른 분위기", en: "Different vibe" }, { ko: "더 가까운 데", en: "Closer option" }, { ko: "예산은 어때?", en: "Budget check" }],
  },
  {
    id: "in-it-food-2",
    characterId: "rina",
    segmentIds: ["in-it"],
    intents: ["food"],
    tags: ["food", "in-it", "rina"],
    text: { ko: "리나 기준으로 지금 배고프면 을지로 우래옥 쪽이 맞아. 채식 가능 여부를 먼저 보는 기준으로 재료·영업은 방문 전에 한 번만 확인해 줘.", en: "With Rina's taste, Uraeok fits a hungry turn. checking vegetarian-friendliness first like Rina Double-check hours and ingredients before you go." },
    placeHints: ["uraeok"],
    chipFollowups: [{ ko: "다른 분위기", en: "Different vibe" }, { ko: "더 가까운 데", en: "Closer option" }, { ko: "예산은 어때?", en: "Budget check" }],
  },
  {
    id: "in-it-night-1",
    characterId: "rina",
    segmentIds: ["in-it"],
    intents: ["night"],
    tags: ["night", "in-it", "rina"],
    text: { ko: "늦은 시간이면 리나는 을지로 노가리를 먼저 떠올려. 채식 가능 여부를 먼저 보는 기준으로 너무 늦으면 영업 마감만 확인하고 가자.", en: "For a late hour, Rina leans Euljiro nogari alley. checking vegetarian-friendliness first like Rina Confirm closing time if it is already late." },
    placeHints: ["euljiro-nogari"],
    chipFollowups: [{ ko: "야식 가볍게", en: "Lighter late bite" }, { ko: "산책으로 바꿀까", en: "Switch to a walk" }, { ko: "다른 밤 코스", en: "Another night pick" }],
  },
  {
    id: "in-it-night-2",
    characterId: "rina",
    segmentIds: ["in-it"],
    intents: ["night"],
    tags: ["night", "in-it", "rina"],
    text: { ko: "늦은 시간이면 리나는 낙산공원를 먼저 떠올려. 채식 가능 여부를 먼저 보는 기준으로 너무 늦으면 영업 마감만 확인하고 가자.", en: "For a late hour, Rina leans Naksan Park. checking vegetarian-friendliness first like Rina Confirm closing time if it is already late." },
    placeHints: ["naksan"],
    chipFollowups: [{ ko: "야식 가볍게", en: "Lighter late bite" }, { ko: "산책으로 바꿀까", en: "Switch to a walk" }, { ko: "다른 밤 코스", en: "Another night pick" }],
  },
  {
    id: "in-it-cafe-1",
    characterId: "rina",
    segmentIds: ["in-it"],
    intents: ["cafe"],
    tags: ["cafe", "in-it", "rina"],
    text: { ko: "잠깐 쉬려면 성수 카페 거리가 무난해. 채식 가능 여부를 먼저 보는 기준으로 웨이팅은 현장 기준으로만 봐 줘.", en: "For a short pause, Seongsu cafe streets works. checking vegetarian-friendliness first like Rina Treat wait times as on-site only." },
    placeHints: ["seongsu-onion"],
    chipFollowups: [{ ko: "디저트", en: "Dessert" }, { ko: "작업하기 좋게", en: "Good for laptop" }, { ko: "근처 산책", en: "Nearby walk" }],
  },
  {
    id: "in-it-cafe-2",
    characterId: "rina",
    segmentIds: ["in-it"],
    intents: ["cafe"],
    tags: ["cafe", "in-it", "rina"],
    text: { ko: "잠깐 쉬려면 커먼그라운드가 무난해. 채식 가능 여부를 먼저 보는 기준으로 웨이팅은 현장 기준으로만 봐 줘.", en: "For a short pause, Common Ground works. checking vegetarian-friendliness first like Rina Treat wait times as on-site only." },
    placeHints: ["common-ground"],
    chipFollowups: [{ ko: "디저트", en: "Dessert" }, { ko: "작업하기 좋게", en: "Good for laptop" }, { ko: "근처 산책", en: "Nearby walk" }],
  },
  {
    id: "in-it-followup-1",
    characterId: "rina",
    segmentIds: ["in-it"],
    intents: ["followup"],
    tags: ["followup", "in-it"],
    text: { ko: "좋아. 그다음으로는 진주집를 이어서 볼까, 아니면 조건을 바꿀까?", en: "Nice. Next we can stay with Jinju-jip, or change the constraint." },
    placeHints: ["jinjujip"],
    chipFollowups: [{ ko: "여기로 갈게", en: "I will go here" }, { ko: "다른 후보", en: "Another option" }, { ko: "조건 바꾸기", en: "Change filters" }],
  },
  {
    id: "me-biz-halal-1",
    characterId: "maya",
    segmentIds: ["me-biz"],
    intents: ["halal"],
    tags: ["halal", "me-biz", "maya"],
    text: { ko: "돼지고기 빼는 흐름이면 이태원 케밥를 먼저 볼게. 할랄 인증·조리 도구·알코올은 별도 확인이 필요해.", en: "For a pork-free path, I look at Itaewon kebab first. Halal certification, utensils, and alcohol need separate checks." },
    placeHints: ["itaewon-kebab"],
    chipFollowups: [{ ko: "다른 무돼지고기", en: "Another no-pork" }, { ko: "야식도 괜찮아?", en: "Late-night OK?" }, { ko: "채식에 가깝게", en: "Closer to veg" }],
  },
  {
    id: "me-biz-food-1",
    characterId: "maya",
    segmentIds: ["me-biz"],
    intents: ["food"],
    tags: ["food", "me-biz", "maya"],
    text: { ko: "마야 기준으로 지금 배고프면 진주집 쪽이 맞아. 식사 제약을 먼저 챙기는 기준으로 재료·영업은 방문 전에 한 번만 확인해 줘.", en: "With Maya's taste, Jinju-jip fits a hungry turn. leading with dining constraints the way Maya does Double-check hours and ingredients before you go." },
    placeHints: ["jinjujip"],
    chipFollowups: [{ ko: "다른 분위기", en: "Different vibe" }, { ko: "더 가까운 데", en: "Closer option" }, { ko: "예산은 어때?", en: "Budget check" }],
  },
  {
    id: "me-biz-food-2",
    characterId: "maya",
    segmentIds: ["me-biz"],
    intents: ["food"],
    tags: ["food", "me-biz", "maya"],
    text: { ko: "마야 기준으로 지금 배고프면 을지로 우래옥 쪽이 맞아. 식사 제약을 먼저 챙기는 기준으로 재료·영업은 방문 전에 한 번만 확인해 줘.", en: "With Maya's taste, Uraeok fits a hungry turn. leading with dining constraints the way Maya does Double-check hours and ingredients before you go." },
    placeHints: ["uraeok"],
    chipFollowups: [{ ko: "다른 분위기", en: "Different vibe" }, { ko: "더 가까운 데", en: "Closer option" }, { ko: "예산은 어때?", en: "Budget check" }],
  },
  {
    id: "me-biz-cafe-1",
    characterId: "maya",
    segmentIds: ["me-biz"],
    intents: ["cafe"],
    tags: ["cafe", "me-biz", "maya"],
    text: { ko: "잠깐 쉬려면 성수 카페 거리가 무난해. 식사 제약을 먼저 챙기는 기준으로 웨이팅은 현장 기준으로만 봐 줘.", en: "For a short pause, Seongsu cafe streets works. leading with dining constraints the way Maya does Treat wait times as on-site only." },
    placeHints: ["seongsu-onion"],
    chipFollowups: [{ ko: "디저트", en: "Dessert" }, { ko: "작업하기 좋게", en: "Good for laptop" }, { ko: "근처 산책", en: "Nearby walk" }],
  },
  {
    id: "me-biz-cafe-2",
    characterId: "maya",
    segmentIds: ["me-biz"],
    intents: ["cafe"],
    tags: ["cafe", "me-biz", "maya"],
    text: { ko: "잠깐 쉬려면 커먼그라운드가 무난해. 식사 제약을 먼저 챙기는 기준으로 웨이팅은 현장 기준으로만 봐 줘.", en: "For a short pause, Common Ground works. leading with dining constraints the way Maya does Treat wait times as on-site only." },
    placeHints: ["common-ground"],
    chipFollowups: [{ ko: "디저트", en: "Dessert" }, { ko: "작업하기 좋게", en: "Good for laptop" }, { ko: "근처 산책", en: "Nearby walk" }],
  },
  {
    id: "me-biz-followup-1",
    characterId: "maya",
    segmentIds: ["me-biz"],
    intents: ["followup"],
    tags: ["followup", "me-biz"],
    text: { ko: "좋아. 그다음으로는 진주집를 이어서 볼까, 아니면 조건을 바꿀까?", en: "Nice. Next we can stay with Jinju-jip, or change the constraint." },
    placeHints: ["jinjujip"],
    chipFollowups: [{ ko: "여기로 갈게", en: "I will go here" }, { ko: "다른 후보", en: "Another option" }, { ko: "조건 바꾸기", en: "Change filters" }],
  },
  {
    id: "ru-cis-food-1",
    characterId: "nuri",
    segmentIds: ["ru-cis"],
    intents: ["food"],
    tags: ["food", "ru-cis", "nuri"],
    text: { ko: "누리 기준으로 지금 배고프면 진주집 쪽이 맞아. 걸어갈 수 있는 동네 동선 기준으로 재료·영업은 방문 전에 한 번만 확인해 줘.", en: "With Nuri's taste, Jinju-jip fits a hungry turn. using walkable neighborhood logic like Nuri Double-check hours and ingredients before you go." },
    placeHints: ["jinjujip"],
    chipFollowups: [{ ko: "다른 분위기", en: "Different vibe" }, { ko: "더 가까운 데", en: "Closer option" }, { ko: "예산은 어때?", en: "Budget check" }],
  },
  {
    id: "ru-cis-food-2",
    characterId: "nuri",
    segmentIds: ["ru-cis"],
    intents: ["food"],
    tags: ["food", "ru-cis", "nuri"],
    text: { ko: "누리 기준으로 지금 배고프면 을지로 우래옥 쪽이 맞아. 걸어갈 수 있는 동네 동선 기준으로 재료·영업은 방문 전에 한 번만 확인해 줘.", en: "With Nuri's taste, Uraeok fits a hungry turn. using walkable neighborhood logic like Nuri Double-check hours and ingredients before you go." },
    placeHints: ["uraeok"],
    chipFollowups: [{ ko: "다른 분위기", en: "Different vibe" }, { ko: "더 가까운 데", en: "Closer option" }, { ko: "예산은 어때?", en: "Budget check" }],
  },
  {
    id: "ru-cis-night-1",
    characterId: "nuri",
    segmentIds: ["ru-cis"],
    intents: ["night"],
    tags: ["night", "ru-cis", "nuri"],
    text: { ko: "늦은 시간이면 누리는 을지로 노가리를 먼저 떠올려. 걸어갈 수 있는 동네 동선 기준으로 너무 늦으면 영업 마감만 확인하고 가자.", en: "For a late hour, Nuri leans Euljiro nogari alley. using walkable neighborhood logic like Nuri Confirm closing time if it is already late." },
    placeHints: ["euljiro-nogari"],
    chipFollowups: [{ ko: "야식 가볍게", en: "Lighter late bite" }, { ko: "산책으로 바꿀까", en: "Switch to a walk" }, { ko: "다른 밤 코스", en: "Another night pick" }],
  },
  {
    id: "ru-cis-night-2",
    characterId: "nuri",
    segmentIds: ["ru-cis"],
    intents: ["night"],
    tags: ["night", "ru-cis", "nuri"],
    text: { ko: "늦은 시간이면 누리는 낙산공원를 먼저 떠올려. 걸어갈 수 있는 동네 동선 기준으로 너무 늦으면 영업 마감만 확인하고 가자.", en: "For a late hour, Nuri leans Naksan Park. using walkable neighborhood logic like Nuri Confirm closing time if it is already late." },
    placeHints: ["naksan"],
    chipFollowups: [{ ko: "야식 가볍게", en: "Lighter late bite" }, { ko: "산책으로 바꿀까", en: "Switch to a walk" }, { ko: "다른 밤 코스", en: "Another night pick" }],
  },
  {
    id: "ru-cis-walk-1",
    characterId: "nuri",
    segmentIds: ["ru-cis"],
    intents: ["walk"],
    tags: ["walk", "ru-cis", "nuri"],
    text: { ko: "걷기 좋은 코스로는 서울숲가 무난해. 걸어갈 수 있는 동네 동선 기준으로 비 오면 실내로 바로 바꿔 줄게.", en: "For a walkable stretch, Seoul Forest is steady. using walkable neighborhood logic like Nuri If it rains we switch indoors." },
    placeHints: ["seoul-forest"],
    chipFollowups: [{ ko: "더 조용하게", en: "Quieter path" }, { ko: "짧게만", en: "Keep it short" }, { ko: "카페로 이어서", en: "Then a cafe" }],
  },
  {
    id: "ru-cis-walk-2",
    characterId: "nuri",
    segmentIds: ["ru-cis"],
    intents: ["walk"],
    tags: ["walk", "ru-cis", "nuri"],
    text: { ko: "걷기 좋은 코스로는 뚝섬한강공원가 무난해. 걸어갈 수 있는 동네 동선 기준으로 비 오면 실내로 바로 바꿔 줄게.", en: "For a walkable stretch, Ttukseom Hangang Park is steady. using walkable neighborhood logic like Nuri If it rains we switch indoors." },
    placeHints: ["ttukseom"],
    chipFollowups: [{ ko: "더 조용하게", en: "Quieter path" }, { ko: "짧게만", en: "Keep it short" }, { ko: "카페로 이어서", en: "Then a cafe" }],
  },
  {
    id: "ru-cis-followup-1",
    characterId: "nuri",
    segmentIds: ["ru-cis"],
    intents: ["followup"],
    tags: ["followup", "ru-cis"],
    text: { ko: "좋아. 그다음으로는 진주집를 이어서 볼까, 아니면 조건을 바꿀까?", en: "Nice. Next we can stay with Jinju-jip, or change the constraint." },
    placeHints: ["jinjujip"],
    chipFollowups: [{ ko: "여기로 갈게", en: "I will go here" }, { ko: "다른 후보", en: "Another option" }, { ko: "조건 바꾸기", en: "Change filters" }],
  },
  {
    id: "latam-food-1",
    characterId: "sori",
    segmentIds: ["latam"],
    intents: ["food"],
    tags: ["food", "latam", "sori"],
    text: { ko: "소리 기준으로 지금 배고프면 진주집 쪽이 맞아. 관광 함정보다 취향을 우선하는 기준으로 재료·영업은 방문 전에 한 번만 확인해 줘.", en: "With Sori's taste, Jinju-jip fits a hungry turn. preferring taste over tourist traps like Sori Double-check hours and ingredients before you go." },
    placeHints: ["jinjujip"],
    chipFollowups: [{ ko: "다른 분위기", en: "Different vibe" }, { ko: "더 가까운 데", en: "Closer option" }, { ko: "예산은 어때?", en: "Budget check" }],
  },
  {
    id: "latam-food-2",
    characterId: "sori",
    segmentIds: ["latam"],
    intents: ["food"],
    tags: ["food", "latam", "sori"],
    text: { ko: "소리 기준으로 지금 배고프면 을지로 우래옥 쪽이 맞아. 관광 함정보다 취향을 우선하는 기준으로 재료·영업은 방문 전에 한 번만 확인해 줘.", en: "With Sori's taste, Uraeok fits a hungry turn. preferring taste over tourist traps like Sori Double-check hours and ingredients before you go." },
    placeHints: ["uraeok"],
    chipFollowups: [{ ko: "다른 분위기", en: "Different vibe" }, { ko: "더 가까운 데", en: "Closer option" }, { ko: "예산은 어때?", en: "Budget check" }],
  },
  {
    id: "latam-night-1",
    characterId: "sori",
    segmentIds: ["latam"],
    intents: ["night"],
    tags: ["night", "latam", "sori"],
    text: { ko: "늦은 시간이면 소리는 을지로 노가리를 먼저 떠올려. 관광 함정보다 취향을 우선하는 기준으로 너무 늦으면 영업 마감만 확인하고 가자.", en: "For a late hour, Sori leans Euljiro nogari alley. preferring taste over tourist traps like Sori Confirm closing time if it is already late." },
    placeHints: ["euljiro-nogari"],
    chipFollowups: [{ ko: "야식 가볍게", en: "Lighter late bite" }, { ko: "산책으로 바꿀까", en: "Switch to a walk" }, { ko: "다른 밤 코스", en: "Another night pick" }],
  },
  {
    id: "latam-night-2",
    characterId: "sori",
    segmentIds: ["latam"],
    intents: ["night"],
    tags: ["night", "latam", "sori"],
    text: { ko: "늦은 시간이면 소리는 낙산공원를 먼저 떠올려. 관광 함정보다 취향을 우선하는 기준으로 너무 늦으면 영업 마감만 확인하고 가자.", en: "For a late hour, Sori leans Naksan Park. preferring taste over tourist traps like Sori Confirm closing time if it is already late." },
    placeHints: ["naksan"],
    chipFollowups: [{ ko: "야식 가볍게", en: "Lighter late bite" }, { ko: "산책으로 바꿀까", en: "Switch to a walk" }, { ko: "다른 밤 코스", en: "Another night pick" }],
  },
  {
    id: "latam-walk-1",
    characterId: "sori",
    segmentIds: ["latam"],
    intents: ["walk"],
    tags: ["walk", "latam", "sori"],
    text: { ko: "걷기 좋은 코스로는 서울숲가 무난해. 관광 함정보다 취향을 우선하는 기준으로 비 오면 실내로 바로 바꿔 줄게.", en: "For a walkable stretch, Seoul Forest is steady. preferring taste over tourist traps like Sori If it rains we switch indoors." },
    placeHints: ["seoul-forest"],
    chipFollowups: [{ ko: "더 조용하게", en: "Quieter path" }, { ko: "짧게만", en: "Keep it short" }, { ko: "카페로 이어서", en: "Then a cafe" }],
  },
  {
    id: "latam-walk-2",
    characterId: "sori",
    segmentIds: ["latam"],
    intents: ["walk"],
    tags: ["walk", "latam", "sori"],
    text: { ko: "걷기 좋은 코스로는 뚝섬한강공원가 무난해. 관광 함정보다 취향을 우선하는 기준으로 비 오면 실내로 바로 바꿔 줄게.", en: "For a walkable stretch, Ttukseom Hangang Park is steady. preferring taste over tourist traps like Sori If it rains we switch indoors." },
    placeHints: ["ttukseom"],
    chipFollowups: [{ ko: "더 조용하게", en: "Quieter path" }, { ko: "짧게만", en: "Keep it short" }, { ko: "카페로 이어서", en: "Then a cafe" }],
  },
  {
    id: "latam-followup-1",
    characterId: "sori",
    segmentIds: ["latam"],
    intents: ["followup"],
    tags: ["followup", "latam"],
    text: { ko: "좋아. 그다음으로는 진주집를 이어서 볼까, 아니면 조건을 바꿀까?", en: "Nice. Next we can stay with Jinju-jip, or change the constraint." },
    placeHints: ["jinjujip"],
    chipFollowups: [{ ko: "여기로 갈게", en: "I will go here" }, { ko: "다른 후보", en: "Another option" }, { ko: "조건 바꾸기", en: "Change filters" }],
  },
  {
    id: "k-content-kcontent-1",
    characterId: "hana",
    segmentIds: ["k-content"],
    intents: ["kcontent"],
    tags: ["kcontent", "k-content", "hana"],
    text: { ko: "K-콘텐츠 감성이면 성수 카페 거리 쪽이 사진·거리 무드에 잘 맞아. 실시간 팝업·공연은 확인 없이 말하지 않을게.", en: "For K-content vibes, Seongsu cafe streets fits street and photo mood. I will not invent live pop-ups or tickets." },
    placeHints: ["seongsu-onion"],
    chipFollowups: [{ ko: "성수 더", en: "More Seongsu" }, { ko: "카페부터", en: "Cafe first" }, { ko: "산책 코스", en: "A walk route" }],
  },
  {
    id: "k-content-kcontent-2",
    characterId: "hana",
    segmentIds: ["k-content"],
    intents: ["kcontent"],
    tags: ["kcontent", "k-content", "hana"],
    text: { ko: "K-콘텐츠 감성이면 커먼그라운드 쪽이 사진·거리 무드에 잘 맞아. 실시간 팝업·공연은 확인 없이 말하지 않을게.", en: "For K-content vibes, Common Ground fits street and photo mood. I will not invent live pop-ups or tickets." },
    placeHints: ["common-ground"],
    chipFollowups: [{ ko: "성수 더", en: "More Seongsu" }, { ko: "카페부터", en: "Cafe first" }, { ko: "산책 코스", en: "A walk route" }],
  },
  {
    id: "k-content-cafe-1",
    characterId: "hana",
    segmentIds: ["k-content"],
    intents: ["cafe"],
    tags: ["cafe", "k-content", "hana"],
    text: { ko: "잠깐 쉬려면 성수 카페 거리가 무난해. 거리·감성·인증샷 무드를 보는 기준으로 웨이팅은 현장 기준으로만 봐 줘.", en: "For a short pause, Seongsu cafe streets works. leaning street mood and photo vibes like Hana Treat wait times as on-site only." },
    placeHints: ["seongsu-onion"],
    chipFollowups: [{ ko: "디저트", en: "Dessert" }, { ko: "작업하기 좋게", en: "Good for laptop" }, { ko: "근처 산책", en: "Nearby walk" }],
  },
  {
    id: "k-content-cafe-2",
    characterId: "hana",
    segmentIds: ["k-content"],
    intents: ["cafe"],
    tags: ["cafe", "k-content", "hana"],
    text: { ko: "잠깐 쉬려면 커먼그라운드가 무난해. 거리·감성·인증샷 무드를 보는 기준으로 웨이팅은 현장 기준으로만 봐 줘.", en: "For a short pause, Common Ground works. leaning street mood and photo vibes like Hana Treat wait times as on-site only." },
    placeHints: ["common-ground"],
    chipFollowups: [{ ko: "디저트", en: "Dessert" }, { ko: "작업하기 좋게", en: "Good for laptop" }, { ko: "근처 산책", en: "Nearby walk" }],
  },
  {
    id: "k-content-walk-1",
    characterId: "hana",
    segmentIds: ["k-content"],
    intents: ["walk"],
    tags: ["walk", "k-content", "hana"],
    text: { ko: "걷기 좋은 코스로는 서울숲가 무난해. 거리·감성·인증샷 무드를 보는 기준으로 비 오면 실내로 바로 바꿔 줄게.", en: "For a walkable stretch, Seoul Forest is steady. leaning street mood and photo vibes like Hana If it rains we switch indoors." },
    placeHints: ["seoul-forest"],
    chipFollowups: [{ ko: "더 조용하게", en: "Quieter path" }, { ko: "짧게만", en: "Keep it short" }, { ko: "카페로 이어서", en: "Then a cafe" }],
  },
  {
    id: "k-content-walk-2",
    characterId: "hana",
    segmentIds: ["k-content"],
    intents: ["walk"],
    tags: ["walk", "k-content", "hana"],
    text: { ko: "걷기 좋은 코스로는 뚝섬한강공원가 무난해. 거리·감성·인증샷 무드를 보는 기준으로 비 오면 실내로 바로 바꿔 줄게.", en: "For a walkable stretch, Ttukseom Hangang Park is steady. leaning street mood and photo vibes like Hana If it rains we switch indoors." },
    placeHints: ["ttukseom"],
    chipFollowups: [{ ko: "더 조용하게", en: "Quieter path" }, { ko: "짧게만", en: "Keep it short" }, { ko: "카페로 이어서", en: "Then a cafe" }],
  },
  {
    id: "k-content-food-1",
    characterId: "hana",
    segmentIds: ["k-content"],
    intents: ["food"],
    tags: ["food", "k-content", "hana"],
    text: { ko: "하나 기준으로 지금 배고프면 진주집 쪽이 맞아. 거리·감성·인증샷 무드를 보는 기준으로 재료·영업은 방문 전에 한 번만 확인해 줘.", en: "With Hana's taste, Jinju-jip fits a hungry turn. leaning street mood and photo vibes like Hana Double-check hours and ingredients before you go." },
    placeHints: ["jinjujip"],
    chipFollowups: [{ ko: "다른 분위기", en: "Different vibe" }, { ko: "더 가까운 데", en: "Closer option" }, { ko: "예산은 어때?", en: "Budget check" }],
  },
  {
    id: "k-content-food-2",
    characterId: "hana",
    segmentIds: ["k-content"],
    intents: ["food"],
    tags: ["food", "k-content", "hana"],
    text: { ko: "하나 기준으로 지금 배고프면 을지로 우래옥 쪽이 맞아. 거리·감성·인증샷 무드를 보는 기준으로 재료·영업은 방문 전에 한 번만 확인해 줘.", en: "With Hana's taste, Uraeok fits a hungry turn. leaning street mood and photo vibes like Hana Double-check hours and ingredients before you go." },
    placeHints: ["uraeok"],
    chipFollowups: [{ ko: "다른 분위기", en: "Different vibe" }, { ko: "더 가까운 데", en: "Closer option" }, { ko: "예산은 어때?", en: "Budget check" }],
  },
  {
    id: "k-content-followup-1",
    characterId: "hana",
    segmentIds: ["k-content"],
    intents: ["followup"],
    tags: ["followup", "k-content"],
    text: { ko: "좋아. 그다음으로는 진주집를 이어서 볼까, 아니면 조건을 바꿀까?", en: "Nice. Next we can stay with Jinju-jip, or change the constraint." },
    placeHints: ["jinjujip"],
    chipFollowups: [{ ko: "여기로 갈게", en: "I will go here" }, { ko: "다른 후보", en: "Another option" }, { ko: "조건 바꾸기", en: "Change filters" }],
  },
  {
    id: "lgbtq-safe-safety-1",
    characterId: "dal",
    segmentIds: ["lgbtq-safe"],
    intents: ["safety"],
    tags: ["safety", "lgbtq-safe", "dal"],
    text: { ko: "편하게 머물 수 있는 쪽으로는 익선동를 우선할게. 사람 밀도·시간대는 그날마다 다르니 무리한 단정은 안 할게.", en: "For a comfortable feel, I prioritize Ikseon-dong. Crowd and timing change daily, so I will not overclaim." },
    placeHints: ["ikseon"],
    chipFollowups: [{ ko: "조용한 카페", en: "Quiet cafe" }, { ko: "밝은 골목", en: "Brighter street" }, { ko: "가까운 곳", en: "Closer spot" }],
  },
  {
    id: "lgbtq-safe-safety-2",
    characterId: "dal",
    segmentIds: ["lgbtq-safe"],
    intents: ["safety"],
    tags: ["safety", "lgbtq-safe", "dal"],
    text: { ko: "편하게 머물 수 있는 쪽으로는 서울숲를 우선할게. 사람 밀도·시간대는 그날마다 다르니 무리한 단정은 안 할게.", en: "For a comfortable feel, I prioritize Seoul Forest. Crowd and timing change daily, so I will not overclaim." },
    placeHints: ["seoul-forest"],
    chipFollowups: [{ ko: "조용한 카페", en: "Quiet cafe" }, { ko: "밝은 골목", en: "Brighter street" }, { ko: "가까운 곳", en: "Closer spot" }],
  },
  {
    id: "lgbtq-safe-cafe-1",
    characterId: "dal",
    segmentIds: ["lgbtq-safe"],
    intents: ["cafe"],
    tags: ["cafe", "lgbtq-safe", "dal"],
    text: { ko: "잠깐 쉬려면 성수 카페 거리가 무난해. 속도·밀도·편안함을 보는 기준으로 웨이팅은 현장 기준으로만 봐 줘.", en: "For a short pause, Seongsu cafe streets works. watching pace, density, and ease like Dal Treat wait times as on-site only." },
    placeHints: ["seongsu-onion"],
    chipFollowups: [{ ko: "디저트", en: "Dessert" }, { ko: "작업하기 좋게", en: "Good for laptop" }, { ko: "근처 산책", en: "Nearby walk" }],
  },
  {
    id: "lgbtq-safe-cafe-2",
    characterId: "dal",
    segmentIds: ["lgbtq-safe"],
    intents: ["cafe"],
    tags: ["cafe", "lgbtq-safe", "dal"],
    text: { ko: "잠깐 쉬려면 커먼그라운드가 무난해. 속도·밀도·편안함을 보는 기준으로 웨이팅은 현장 기준으로만 봐 줘.", en: "For a short pause, Common Ground works. watching pace, density, and ease like Dal Treat wait times as on-site only." },
    placeHints: ["common-ground"],
    chipFollowups: [{ ko: "디저트", en: "Dessert" }, { ko: "작업하기 좋게", en: "Good for laptop" }, { ko: "근처 산책", en: "Nearby walk" }],
  },
  {
    id: "lgbtq-safe-walk-1",
    characterId: "dal",
    segmentIds: ["lgbtq-safe"],
    intents: ["walk"],
    tags: ["walk", "lgbtq-safe", "dal"],
    text: { ko: "걷기 좋은 코스로는 서울숲가 무난해. 속도·밀도·편안함을 보는 기준으로 비 오면 실내로 바로 바꿔 줄게.", en: "For a walkable stretch, Seoul Forest is steady. watching pace, density, and ease like Dal If it rains we switch indoors." },
    placeHints: ["seoul-forest"],
    chipFollowups: [{ ko: "더 조용하게", en: "Quieter path" }, { ko: "짧게만", en: "Keep it short" }, { ko: "카페로 이어서", en: "Then a cafe" }],
  },
  {
    id: "lgbtq-safe-walk-2",
    characterId: "dal",
    segmentIds: ["lgbtq-safe"],
    intents: ["walk"],
    tags: ["walk", "lgbtq-safe", "dal"],
    text: { ko: "걷기 좋은 코스로는 뚝섬한강공원가 무난해. 속도·밀도·편안함을 보는 기준으로 비 오면 실내로 바로 바꿔 줄게.", en: "For a walkable stretch, Ttukseom Hangang Park is steady. watching pace, density, and ease like Dal If it rains we switch indoors." },
    placeHints: ["ttukseom"],
    chipFollowups: [{ ko: "더 조용하게", en: "Quieter path" }, { ko: "짧게만", en: "Keep it short" }, { ko: "카페로 이어서", en: "Then a cafe" }],
  },
  {
    id: "lgbtq-safe-food-1",
    characterId: "dal",
    segmentIds: ["lgbtq-safe"],
    intents: ["food"],
    tags: ["food", "lgbtq-safe", "dal"],
    text: { ko: "달 기준으로 지금 배고프면 진주집 쪽이 맞아. 속도·밀도·편안함을 보는 기준으로 재료·영업은 방문 전에 한 번만 확인해 줘.", en: "With Dal's taste, Jinju-jip fits a hungry turn. watching pace, density, and ease like Dal Double-check hours and ingredients before you go." },
    placeHints: ["jinjujip"],
    chipFollowups: [{ ko: "다른 분위기", en: "Different vibe" }, { ko: "더 가까운 데", en: "Closer option" }, { ko: "예산은 어때?", en: "Budget check" }],
  },
  {
    id: "lgbtq-safe-food-2",
    characterId: "dal",
    segmentIds: ["lgbtq-safe"],
    intents: ["food"],
    tags: ["food", "lgbtq-safe", "dal"],
    text: { ko: "달 기준으로 지금 배고프면 을지로 우래옥 쪽이 맞아. 속도·밀도·편안함을 보는 기준으로 재료·영업은 방문 전에 한 번만 확인해 줘.", en: "With Dal's taste, Uraeok fits a hungry turn. watching pace, density, and ease like Dal Double-check hours and ingredients before you go." },
    placeHints: ["uraeok"],
    chipFollowups: [{ ko: "다른 분위기", en: "Different vibe" }, { ko: "더 가까운 데", en: "Closer option" }, { ko: "예산은 어때?", en: "Budget check" }],
  },
  {
    id: "lgbtq-safe-followup-1",
    characterId: "dal",
    segmentIds: ["lgbtq-safe"],
    intents: ["followup"],
    tags: ["followup", "lgbtq-safe"],
    text: { ko: "좋아. 그다음으로는 진주집를 이어서 볼까, 아니면 조건을 바꿀까?", en: "Nice. Next we can stay with Jinju-jip, or change the constraint." },
    placeHints: ["jinjujip"],
    chipFollowups: [{ ko: "여기로 갈게", en: "I will go here" }, { ko: "다른 후보", en: "Another option" }, { ko: "조건 바꾸기", en: "Change filters" }],
  },
  {
    id: "any-yuki-food",
    characterId: "yuki",
    segmentIds: ["*"],
    intents: ["food"],
    tags: ["food", "wildcard", "yuki"],
    text: { ko: "유키 기준으로 지금 배고프면 진주집 쪽이 맞아. 일본 손님들이 자주 묻던 효율·맵기 기준으로 재료·영업은 방문 전에 한 번만 확인해 줘.", en: "With Yuki's taste, Jinju-jip fits a hungry turn. using the efficient, milder bar Yuki learned from JP guests Double-check hours and ingredients before you go." },
    placeHints: ["jinjujip"],
    chipFollowups: [{ ko: "다른 분위기", en: "Different vibe" }, { ko: "더 가까운 데", en: "Closer option" }, { ko: "예산은 어때?", en: "Budget check" }],
  },
  {
    id: "any-yuki-night",
    characterId: "yuki",
    segmentIds: ["*"],
    intents: ["night"],
    tags: ["night", "wildcard", "yuki"],
    text: { ko: "늦은 시간이면 유키는 을지로 노가리를 먼저 떠올려. 일본 손님들이 자주 묻던 효율·맵기 기준으로 너무 늦으면 영업 마감만 확인하고 가자.", en: "For a late hour, Yuki leans Euljiro nogari alley. using the efficient, milder bar Yuki learned from JP guests Confirm closing time if it is already late." },
    placeHints: ["euljiro-nogari"],
    chipFollowups: [{ ko: "야식 가볍게", en: "Lighter late bite" }, { ko: "산책으로 바꿀까", en: "Switch to a walk" }, { ko: "다른 밤 코스", en: "Another night pick" }],
  },
  {
    id: "any-yuki-walk",
    characterId: "yuki",
    segmentIds: ["*"],
    intents: ["walk"],
    tags: ["walk", "wildcard", "yuki"],
    text: { ko: "걷기 좋은 코스로는 서울숲가 무난해. 일본 손님들이 자주 묻던 효율·맵기 기준으로 비 오면 실내로 바로 바꿔 줄게.", en: "For a walkable stretch, Seoul Forest is steady. using the efficient, milder bar Yuki learned from JP guests If it rains we switch indoors." },
    placeHints: ["seoul-forest"],
    chipFollowups: [{ ko: "더 조용하게", en: "Quieter path" }, { ko: "짧게만", en: "Keep it short" }, { ko: "카페로 이어서", en: "Then a cafe" }],
  },
  {
    id: "any-yuki-budget",
    characterId: "yuki",
    segmentIds: ["*"],
    intents: ["budget"],
    tags: ["budget", "wildcard", "yuki"],
    text: { ko: "지갑 생각이면 광장시장부터. 일본 손님들이 자주 묻던 효율·맵기 기준으로 가격은 매장마다 다르니 메뉴판 기준으로만 말해 줄게.", en: "On a budget, start with Gwangjang Market. using the efficient, milder bar Yuki learned from JP guests I will not invent prices—use the menu you see." },
    placeHints: ["gwangjang"],
    chipFollowups: [{ ko: "더 싸게", en: "Cheaper still" }, { ko: "배부르게", en: "More filling" }, { ko: "걸어서 갈 수 있게", en: "Walkable" }],
  },
  {
    id: "any-yuki-cafe",
    characterId: "yuki",
    segmentIds: ["*"],
    intents: ["cafe"],
    tags: ["cafe", "wildcard", "yuki"],
    text: { ko: "잠깐 쉬려면 성수 카페 거리가 무난해. 일본 손님들이 자주 묻던 효율·맵기 기준으로 웨이팅은 현장 기준으로만 봐 줘.", en: "For a short pause, Seongsu cafe streets works. using the efficient, milder bar Yuki learned from JP guests Treat wait times as on-site only." },
    placeHints: ["seongsu-onion"],
    chipFollowups: [{ ko: "디저트", en: "Dessert" }, { ko: "작업하기 좋게", en: "Good for laptop" }, { ko: "근처 산책", en: "Nearby walk" }],
  },
  {
    id: "any-tom-food",
    characterId: "tom",
    segmentIds: ["*"],
    intents: ["food"],
    tags: ["food", "wildcard", "tom"],
    text: { ko: "톰 기준으로 지금 배고프면 진주집 쪽이 맞아. 값어치와 배부름을 먼저 보는 기준으로 재료·영업은 방문 전에 한 번만 확인해 줘.", en: "With Tom's taste, Jinju-jip fits a hungry turn. favoring value and fullness the way Tom ranks Double-check hours and ingredients before you go." },
    placeHints: ["jinjujip"],
    chipFollowups: [{ ko: "다른 분위기", en: "Different vibe" }, { ko: "더 가까운 데", en: "Closer option" }, { ko: "예산은 어때?", en: "Budget check" }],
  },
  {
    id: "any-tom-night",
    characterId: "tom",
    segmentIds: ["*"],
    intents: ["night"],
    tags: ["night", "wildcard", "tom"],
    text: { ko: "늦은 시간이면 톰는 을지로 노가리를 먼저 떠올려. 값어치와 배부름을 먼저 보는 기준으로 너무 늦으면 영업 마감만 확인하고 가자.", en: "For a late hour, Tom leans Euljiro nogari alley. favoring value and fullness the way Tom ranks Confirm closing time if it is already late." },
    placeHints: ["euljiro-nogari"],
    chipFollowups: [{ ko: "야식 가볍게", en: "Lighter late bite" }, { ko: "산책으로 바꿀까", en: "Switch to a walk" }, { ko: "다른 밤 코스", en: "Another night pick" }],
  },
  {
    id: "any-tom-walk",
    characterId: "tom",
    segmentIds: ["*"],
    intents: ["walk"],
    tags: ["walk", "wildcard", "tom"],
    text: { ko: "걷기 좋은 코스로는 서울숲가 무난해. 값어치와 배부름을 먼저 보는 기준으로 비 오면 실내로 바로 바꿔 줄게.", en: "For a walkable stretch, Seoul Forest is steady. favoring value and fullness the way Tom ranks If it rains we switch indoors." },
    placeHints: ["seoul-forest"],
    chipFollowups: [{ ko: "더 조용하게", en: "Quieter path" }, { ko: "짧게만", en: "Keep it short" }, { ko: "카페로 이어서", en: "Then a cafe" }],
  },
  {
    id: "any-tom-budget",
    characterId: "tom",
    segmentIds: ["*"],
    intents: ["budget"],
    tags: ["budget", "wildcard", "tom"],
    text: { ko: "지갑 생각이면 광장시장부터. 값어치와 배부름을 먼저 보는 기준으로 가격은 매장마다 다르니 메뉴판 기준으로만 말해 줄게.", en: "On a budget, start with Gwangjang Market. favoring value and fullness the way Tom ranks I will not invent prices—use the menu you see." },
    placeHints: ["gwangjang"],
    chipFollowups: [{ ko: "더 싸게", en: "Cheaper still" }, { ko: "배부르게", en: "More filling" }, { ko: "걸어서 갈 수 있게", en: "Walkable" }],
  },
  {
    id: "any-tom-cafe",
    characterId: "tom",
    segmentIds: ["*"],
    intents: ["cafe"],
    tags: ["cafe", "wildcard", "tom"],
    text: { ko: "잠깐 쉬려면 성수 카페 거리가 무난해. 값어치와 배부름을 먼저 보는 기준으로 웨이팅은 현장 기준으로만 봐 줘.", en: "For a short pause, Seongsu cafe streets works. favoring value and fullness the way Tom ranks Treat wait times as on-site only." },
    placeHints: ["seongsu-onion"],
    chipFollowups: [{ ko: "디저트", en: "Dessert" }, { ko: "작업하기 좋게", en: "Good for laptop" }, { ko: "근처 산책", en: "Nearby walk" }],
  },
  {
    id: "any-maya-food",
    characterId: "maya",
    segmentIds: ["*"],
    intents: ["food"],
    tags: ["food", "wildcard", "maya"],
    text: { ko: "마야 기준으로 지금 배고프면 진주집 쪽이 맞아. 식사 제약을 먼저 챙기는 기준으로 재료·영업은 방문 전에 한 번만 확인해 줘.", en: "With Maya's taste, Jinju-jip fits a hungry turn. leading with dining constraints the way Maya does Double-check hours and ingredients before you go." },
    placeHints: ["jinjujip"],
    chipFollowups: [{ ko: "다른 분위기", en: "Different vibe" }, { ko: "더 가까운 데", en: "Closer option" }, { ko: "예산은 어때?", en: "Budget check" }],
  },
  {
    id: "any-maya-night",
    characterId: "maya",
    segmentIds: ["*"],
    intents: ["night"],
    tags: ["night", "wildcard", "maya"],
    text: { ko: "늦은 시간이면 마야는 을지로 노가리를 먼저 떠올려. 식사 제약을 먼저 챙기는 기준으로 너무 늦으면 영업 마감만 확인하고 가자.", en: "For a late hour, Maya leans Euljiro nogari alley. leading with dining constraints the way Maya does Confirm closing time if it is already late." },
    placeHints: ["euljiro-nogari"],
    chipFollowups: [{ ko: "야식 가볍게", en: "Lighter late bite" }, { ko: "산책으로 바꿀까", en: "Switch to a walk" }, { ko: "다른 밤 코스", en: "Another night pick" }],
  },
  {
    id: "any-maya-walk",
    characterId: "maya",
    segmentIds: ["*"],
    intents: ["walk"],
    tags: ["walk", "wildcard", "maya"],
    text: { ko: "걷기 좋은 코스로는 서울숲가 무난해. 식사 제약을 먼저 챙기는 기준으로 비 오면 실내로 바로 바꿔 줄게.", en: "For a walkable stretch, Seoul Forest is steady. leading with dining constraints the way Maya does If it rains we switch indoors." },
    placeHints: ["seoul-forest"],
    chipFollowups: [{ ko: "더 조용하게", en: "Quieter path" }, { ko: "짧게만", en: "Keep it short" }, { ko: "카페로 이어서", en: "Then a cafe" }],
  },
  {
    id: "any-maya-budget",
    characterId: "maya",
    segmentIds: ["*"],
    intents: ["budget"],
    tags: ["budget", "wildcard", "maya"],
    text: { ko: "지갑 생각이면 광장시장부터. 식사 제약을 먼저 챙기는 기준으로 가격은 매장마다 다르니 메뉴판 기준으로만 말해 줄게.", en: "On a budget, start with Gwangjang Market. leading with dining constraints the way Maya does I will not invent prices—use the menu you see." },
    placeHints: ["gwangjang"],
    chipFollowups: [{ ko: "더 싸게", en: "Cheaper still" }, { ko: "배부르게", en: "More filling" }, { ko: "걸어서 갈 수 있게", en: "Walkable" }],
  },
  {
    id: "any-maya-cafe",
    characterId: "maya",
    segmentIds: ["*"],
    intents: ["cafe"],
    tags: ["cafe", "wildcard", "maya"],
    text: { ko: "잠깐 쉬려면 성수 카페 거리가 무난해. 식사 제약을 먼저 챙기는 기준으로 웨이팅은 현장 기준으로만 봐 줘.", en: "For a short pause, Seongsu cafe streets works. leading with dining constraints the way Maya does Treat wait times as on-site only." },
    placeHints: ["seongsu-onion"],
    chipFollowups: [{ ko: "디저트", en: "Dessert" }, { ko: "작업하기 좋게", en: "Good for laptop" }, { ko: "근처 산책", en: "Nearby walk" }],
  },
  {
    id: "any-nuri-food",
    characterId: "nuri",
    segmentIds: ["*"],
    intents: ["food"],
    tags: ["food", "wildcard", "nuri"],
    text: { ko: "누리 기준으로 지금 배고프면 진주집 쪽이 맞아. 걸어갈 수 있는 동네 동선 기준으로 재료·영업은 방문 전에 한 번만 확인해 줘.", en: "With Nuri's taste, Jinju-jip fits a hungry turn. using walkable neighborhood logic like Nuri Double-check hours and ingredients before you go." },
    placeHints: ["jinjujip"],
    chipFollowups: [{ ko: "다른 분위기", en: "Different vibe" }, { ko: "더 가까운 데", en: "Closer option" }, { ko: "예산은 어때?", en: "Budget check" }],
  },
  {
    id: "any-nuri-night",
    characterId: "nuri",
    segmentIds: ["*"],
    intents: ["night"],
    tags: ["night", "wildcard", "nuri"],
    text: { ko: "늦은 시간이면 누리는 을지로 노가리를 먼저 떠올려. 걸어갈 수 있는 동네 동선 기준으로 너무 늦으면 영업 마감만 확인하고 가자.", en: "For a late hour, Nuri leans Euljiro nogari alley. using walkable neighborhood logic like Nuri Confirm closing time if it is already late." },
    placeHints: ["euljiro-nogari"],
    chipFollowups: [{ ko: "야식 가볍게", en: "Lighter late bite" }, { ko: "산책으로 바꿀까", en: "Switch to a walk" }, { ko: "다른 밤 코스", en: "Another night pick" }],
  },
  {
    id: "any-nuri-walk",
    characterId: "nuri",
    segmentIds: ["*"],
    intents: ["walk"],
    tags: ["walk", "wildcard", "nuri"],
    text: { ko: "걷기 좋은 코스로는 서울숲가 무난해. 걸어갈 수 있는 동네 동선 기준으로 비 오면 실내로 바로 바꿔 줄게.", en: "For a walkable stretch, Seoul Forest is steady. using walkable neighborhood logic like Nuri If it rains we switch indoors." },
    placeHints: ["seoul-forest"],
    chipFollowups: [{ ko: "더 조용하게", en: "Quieter path" }, { ko: "짧게만", en: "Keep it short" }, { ko: "카페로 이어서", en: "Then a cafe" }],
  },
  {
    id: "any-nuri-budget",
    characterId: "nuri",
    segmentIds: ["*"],
    intents: ["budget"],
    tags: ["budget", "wildcard", "nuri"],
    text: { ko: "지갑 생각이면 광장시장부터. 걸어갈 수 있는 동네 동선 기준으로 가격은 매장마다 다르니 메뉴판 기준으로만 말해 줄게.", en: "On a budget, start with Gwangjang Market. using walkable neighborhood logic like Nuri I will not invent prices—use the menu you see." },
    placeHints: ["gwangjang"],
    chipFollowups: [{ ko: "더 싸게", en: "Cheaper still" }, { ko: "배부르게", en: "More filling" }, { ko: "걸어서 갈 수 있게", en: "Walkable" }],
  },
  {
    id: "any-nuri-cafe",
    characterId: "nuri",
    segmentIds: ["*"],
    intents: ["cafe"],
    tags: ["cafe", "wildcard", "nuri"],
    text: { ko: "잠깐 쉬려면 성수 카페 거리가 무난해. 걸어갈 수 있는 동네 동선 기준으로 웨이팅은 현장 기준으로만 봐 줘.", en: "For a short pause, Seongsu cafe streets works. using walkable neighborhood logic like Nuri Treat wait times as on-site only." },
    placeHints: ["seongsu-onion"],
    chipFollowups: [{ ko: "디저트", en: "Dessert" }, { ko: "작업하기 좋게", en: "Good for laptop" }, { ko: "근처 산책", en: "Nearby walk" }],
  },
  {
    id: "any-sori-food",
    characterId: "sori",
    segmentIds: ["*"],
    intents: ["food"],
    tags: ["food", "wildcard", "sori"],
    text: { ko: "소리 기준으로 지금 배고프면 진주집 쪽이 맞아. 관광 함정보다 취향을 우선하는 기준으로 재료·영업은 방문 전에 한 번만 확인해 줘.", en: "With Sori's taste, Jinju-jip fits a hungry turn. preferring taste over tourist traps like Sori Double-check hours and ingredients before you go." },
    placeHints: ["jinjujip"],
    chipFollowups: [{ ko: "다른 분위기", en: "Different vibe" }, { ko: "더 가까운 데", en: "Closer option" }, { ko: "예산은 어때?", en: "Budget check" }],
  },
  {
    id: "any-sori-night",
    characterId: "sori",
    segmentIds: ["*"],
    intents: ["night"],
    tags: ["night", "wildcard", "sori"],
    text: { ko: "늦은 시간이면 소리는 을지로 노가리를 먼저 떠올려. 관광 함정보다 취향을 우선하는 기준으로 너무 늦으면 영업 마감만 확인하고 가자.", en: "For a late hour, Sori leans Euljiro nogari alley. preferring taste over tourist traps like Sori Confirm closing time if it is already late." },
    placeHints: ["euljiro-nogari"],
    chipFollowups: [{ ko: "야식 가볍게", en: "Lighter late bite" }, { ko: "산책으로 바꿀까", en: "Switch to a walk" }, { ko: "다른 밤 코스", en: "Another night pick" }],
  },
  {
    id: "any-sori-walk",
    characterId: "sori",
    segmentIds: ["*"],
    intents: ["walk"],
    tags: ["walk", "wildcard", "sori"],
    text: { ko: "걷기 좋은 코스로는 서울숲가 무난해. 관광 함정보다 취향을 우선하는 기준으로 비 오면 실내로 바로 바꿔 줄게.", en: "For a walkable stretch, Seoul Forest is steady. preferring taste over tourist traps like Sori If it rains we switch indoors." },
    placeHints: ["seoul-forest"],
    chipFollowups: [{ ko: "더 조용하게", en: "Quieter path" }, { ko: "짧게만", en: "Keep it short" }, { ko: "카페로 이어서", en: "Then a cafe" }],
  },
  {
    id: "any-sori-budget",
    characterId: "sori",
    segmentIds: ["*"],
    intents: ["budget"],
    tags: ["budget", "wildcard", "sori"],
    text: { ko: "지갑 생각이면 광장시장부터. 관광 함정보다 취향을 우선하는 기준으로 가격은 매장마다 다르니 메뉴판 기준으로만 말해 줄게.", en: "On a budget, start with Gwangjang Market. preferring taste over tourist traps like Sori I will not invent prices—use the menu you see." },
    placeHints: ["gwangjang"],
    chipFollowups: [{ ko: "더 싸게", en: "Cheaper still" }, { ko: "배부르게", en: "More filling" }, { ko: "걸어서 갈 수 있게", en: "Walkable" }],
  },
  {
    id: "any-sori-cafe",
    characterId: "sori",
    segmentIds: ["*"],
    intents: ["cafe"],
    tags: ["cafe", "wildcard", "sori"],
    text: { ko: "잠깐 쉬려면 성수 카페 거리가 무난해. 관광 함정보다 취향을 우선하는 기준으로 웨이팅은 현장 기준으로만 봐 줘.", en: "For a short pause, Seongsu cafe streets works. preferring taste over tourist traps like Sori Treat wait times as on-site only." },
    placeHints: ["seongsu-onion"],
    chipFollowups: [{ ko: "디저트", en: "Dessert" }, { ko: "작업하기 좋게", en: "Good for laptop" }, { ko: "근처 산책", en: "Nearby walk" }],
  },
  {
    id: "any-dal-food",
    characterId: "dal",
    segmentIds: ["*"],
    intents: ["food"],
    tags: ["food", "wildcard", "dal"],
    text: { ko: "달 기준으로 지금 배고프면 진주집 쪽이 맞아. 속도·밀도·편안함을 보는 기준으로 재료·영업은 방문 전에 한 번만 확인해 줘.", en: "With Dal's taste, Jinju-jip fits a hungry turn. watching pace, density, and ease like Dal Double-check hours and ingredients before you go." },
    placeHints: ["jinjujip"],
    chipFollowups: [{ ko: "다른 분위기", en: "Different vibe" }, { ko: "더 가까운 데", en: "Closer option" }, { ko: "예산은 어때?", en: "Budget check" }],
  },
  {
    id: "any-dal-night",
    characterId: "dal",
    segmentIds: ["*"],
    intents: ["night"],
    tags: ["night", "wildcard", "dal"],
    text: { ko: "늦은 시간이면 달는 을지로 노가리를 먼저 떠올려. 속도·밀도·편안함을 보는 기준으로 너무 늦으면 영업 마감만 확인하고 가자.", en: "For a late hour, Dal leans Euljiro nogari alley. watching pace, density, and ease like Dal Confirm closing time if it is already late." },
    placeHints: ["euljiro-nogari"],
    chipFollowups: [{ ko: "야식 가볍게", en: "Lighter late bite" }, { ko: "산책으로 바꿀까", en: "Switch to a walk" }, { ko: "다른 밤 코스", en: "Another night pick" }],
  },
  {
    id: "any-dal-walk",
    characterId: "dal",
    segmentIds: ["*"],
    intents: ["walk"],
    tags: ["walk", "wildcard", "dal"],
    text: { ko: "걷기 좋은 코스로는 서울숲가 무난해. 속도·밀도·편안함을 보는 기준으로 비 오면 실내로 바로 바꿔 줄게.", en: "For a walkable stretch, Seoul Forest is steady. watching pace, density, and ease like Dal If it rains we switch indoors." },
    placeHints: ["seoul-forest"],
    chipFollowups: [{ ko: "더 조용하게", en: "Quieter path" }, { ko: "짧게만", en: "Keep it short" }, { ko: "카페로 이어서", en: "Then a cafe" }],
  },
  {
    id: "any-dal-budget",
    characterId: "dal",
    segmentIds: ["*"],
    intents: ["budget"],
    tags: ["budget", "wildcard", "dal"],
    text: { ko: "지갑 생각이면 광장시장부터. 속도·밀도·편안함을 보는 기준으로 가격은 매장마다 다르니 메뉴판 기준으로만 말해 줄게.", en: "On a budget, start with Gwangjang Market. watching pace, density, and ease like Dal I will not invent prices—use the menu you see." },
    placeHints: ["gwangjang"],
    chipFollowups: [{ ko: "더 싸게", en: "Cheaper still" }, { ko: "배부르게", en: "More filling" }, { ko: "걸어서 갈 수 있게", en: "Walkable" }],
  },
  {
    id: "any-dal-cafe",
    characterId: "dal",
    segmentIds: ["*"],
    intents: ["cafe"],
    tags: ["cafe", "wildcard", "dal"],
    text: { ko: "잠깐 쉬려면 성수 카페 거리가 무난해. 속도·밀도·편안함을 보는 기준으로 웨이팅은 현장 기준으로만 봐 줘.", en: "For a short pause, Seongsu cafe streets works. watching pace, density, and ease like Dal Treat wait times as on-site only." },
    placeHints: ["seongsu-onion"],
    chipFollowups: [{ ko: "디저트", en: "Dessert" }, { ko: "작업하기 좋게", en: "Good for laptop" }, { ko: "근처 산책", en: "Nearby walk" }],
  },
  {
    id: "any-rina-food",
    characterId: "rina",
    segmentIds: ["*"],
    intents: ["food"],
    tags: ["food", "wildcard", "rina"],
    text: { ko: "리나 기준으로 지금 배고프면 진주집 쪽이 맞아. 채식 가능 여부를 먼저 보는 기준으로 재료·영업은 방문 전에 한 번만 확인해 줘.", en: "With Rina's taste, Jinju-jip fits a hungry turn. checking vegetarian-friendliness first like Rina Double-check hours and ingredients before you go." },
    placeHints: ["jinjujip"],
    chipFollowups: [{ ko: "다른 분위기", en: "Different vibe" }, { ko: "더 가까운 데", en: "Closer option" }, { ko: "예산은 어때?", en: "Budget check" }],
  },
  {
    id: "any-rina-night",
    characterId: "rina",
    segmentIds: ["*"],
    intents: ["night"],
    tags: ["night", "wildcard", "rina"],
    text: { ko: "늦은 시간이면 리나는 을지로 노가리를 먼저 떠올려. 채식 가능 여부를 먼저 보는 기준으로 너무 늦으면 영업 마감만 확인하고 가자.", en: "For a late hour, Rina leans Euljiro nogari alley. checking vegetarian-friendliness first like Rina Confirm closing time if it is already late." },
    placeHints: ["euljiro-nogari"],
    chipFollowups: [{ ko: "야식 가볍게", en: "Lighter late bite" }, { ko: "산책으로 바꿀까", en: "Switch to a walk" }, { ko: "다른 밤 코스", en: "Another night pick" }],
  },
  {
    id: "any-rina-walk",
    characterId: "rina",
    segmentIds: ["*"],
    intents: ["walk"],
    tags: ["walk", "wildcard", "rina"],
    text: { ko: "걷기 좋은 코스로는 서울숲가 무난해. 채식 가능 여부를 먼저 보는 기준으로 비 오면 실내로 바로 바꿔 줄게.", en: "For a walkable stretch, Seoul Forest is steady. checking vegetarian-friendliness first like Rina If it rains we switch indoors." },
    placeHints: ["seoul-forest"],
    chipFollowups: [{ ko: "더 조용하게", en: "Quieter path" }, { ko: "짧게만", en: "Keep it short" }, { ko: "카페로 이어서", en: "Then a cafe" }],
  },
  {
    id: "any-rina-budget",
    characterId: "rina",
    segmentIds: ["*"],
    intents: ["budget"],
    tags: ["budget", "wildcard", "rina"],
    text: { ko: "지갑 생각이면 광장시장부터. 채식 가능 여부를 먼저 보는 기준으로 가격은 매장마다 다르니 메뉴판 기준으로만 말해 줄게.", en: "On a budget, start with Gwangjang Market. checking vegetarian-friendliness first like Rina I will not invent prices—use the menu you see." },
    placeHints: ["gwangjang"],
    chipFollowups: [{ ko: "더 싸게", en: "Cheaper still" }, { ko: "배부르게", en: "More filling" }, { ko: "걸어서 갈 수 있게", en: "Walkable" }],
  },
  {
    id: "any-rina-cafe",
    characterId: "rina",
    segmentIds: ["*"],
    intents: ["cafe"],
    tags: ["cafe", "wildcard", "rina"],
    text: { ko: "잠깐 쉬려면 성수 카페 거리가 무난해. 채식 가능 여부를 먼저 보는 기준으로 웨이팅은 현장 기준으로만 봐 줘.", en: "For a short pause, Seongsu cafe streets works. checking vegetarian-friendliness first like Rina Treat wait times as on-site only." },
    placeHints: ["seongsu-onion"],
    chipFollowups: [{ ko: "디저트", en: "Dessert" }, { ko: "작업하기 좋게", en: "Good for laptop" }, { ko: "근처 산책", en: "Nearby walk" }],
  },
  {
    id: "any-hana-food",
    characterId: "hana",
    segmentIds: ["*"],
    intents: ["food"],
    tags: ["food", "wildcard", "hana"],
    text: { ko: "하나 기준으로 지금 배고프면 진주집 쪽이 맞아. 거리·감성·인증샷 무드를 보는 기준으로 재료·영업은 방문 전에 한 번만 확인해 줘.", en: "With Hana's taste, Jinju-jip fits a hungry turn. leaning street mood and photo vibes like Hana Double-check hours and ingredients before you go." },
    placeHints: ["jinjujip"],
    chipFollowups: [{ ko: "다른 분위기", en: "Different vibe" }, { ko: "더 가까운 데", en: "Closer option" }, { ko: "예산은 어때?", en: "Budget check" }],
  },
  {
    id: "any-hana-night",
    characterId: "hana",
    segmentIds: ["*"],
    intents: ["night"],
    tags: ["night", "wildcard", "hana"],
    text: { ko: "늦은 시간이면 하나는 을지로 노가리를 먼저 떠올려. 거리·감성·인증샷 무드를 보는 기준으로 너무 늦으면 영업 마감만 확인하고 가자.", en: "For a late hour, Hana leans Euljiro nogari alley. leaning street mood and photo vibes like Hana Confirm closing time if it is already late." },
    placeHints: ["euljiro-nogari"],
    chipFollowups: [{ ko: "야식 가볍게", en: "Lighter late bite" }, { ko: "산책으로 바꿀까", en: "Switch to a walk" }, { ko: "다른 밤 코스", en: "Another night pick" }],
  },
  {
    id: "any-hana-walk",
    characterId: "hana",
    segmentIds: ["*"],
    intents: ["walk"],
    tags: ["walk", "wildcard", "hana"],
    text: { ko: "걷기 좋은 코스로는 서울숲가 무난해. 거리·감성·인증샷 무드를 보는 기준으로 비 오면 실내로 바로 바꿔 줄게.", en: "For a walkable stretch, Seoul Forest is steady. leaning street mood and photo vibes like Hana If it rains we switch indoors." },
    placeHints: ["seoul-forest"],
    chipFollowups: [{ ko: "더 조용하게", en: "Quieter path" }, { ko: "짧게만", en: "Keep it short" }, { ko: "카페로 이어서", en: "Then a cafe" }],
  },
  {
    id: "any-hana-budget",
    characterId: "hana",
    segmentIds: ["*"],
    intents: ["budget"],
    tags: ["budget", "wildcard", "hana"],
    text: { ko: "지갑 생각이면 광장시장부터. 거리·감성·인증샷 무드를 보는 기준으로 가격은 매장마다 다르니 메뉴판 기준으로만 말해 줄게.", en: "On a budget, start with Gwangjang Market. leaning street mood and photo vibes like Hana I will not invent prices—use the menu you see." },
    placeHints: ["gwangjang"],
    chipFollowups: [{ ko: "더 싸게", en: "Cheaper still" }, { ko: "배부르게", en: "More filling" }, { ko: "걸어서 갈 수 있게", en: "Walkable" }],
  },
  {
    id: "any-hana-cafe",
    characterId: "hana",
    segmentIds: ["*"],
    intents: ["cafe"],
    tags: ["cafe", "wildcard", "hana"],
    text: { ko: "잠깐 쉬려면 성수 카페 거리가 무난해. 거리·감성·인증샷 무드를 보는 기준으로 웨이팅은 현장 기준으로만 봐 줘.", en: "For a short pause, Seongsu cafe streets works. leaning street mood and photo vibes like Hana Treat wait times as on-site only." },
    placeHints: ["seongsu-onion"],
    chipFollowups: [{ ko: "디저트", en: "Dessert" }, { ko: "작업하기 좋게", en: "Good for laptop" }, { ko: "근처 산책", en: "Nearby walk" }],
  },
];

export const GOLDEN_CARD_COUNT = 183;

